// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"fmt"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/redis/go-redis/v9"
	"go.mongodb.org/mongo-driver/v2/mongo"
	"go.mongodb.org/mongo-driver/v2/mongo/options"
	"nonoka-im/internal/biz"
	"nonoka-im/internal/conf"
	"nonoka-im/internal/data"
	"nonoka-im/internal/gateway"
	"nonoka-im/internal/metrics"
	"nonoka-im/internal/msgworker"
	"nonoka-im/internal/server"
	"nonoka-im/internal/service"
	"os"
	"time"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, dispatch *conf.Dispatch, gatewayConfig *conf.GatewayConfig, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData, logger)
	authUsecase := biz.NewAuthUsecase(authRepo, auth)
	authService := service.NewAuthService(authUsecase)
	universalClient := provideRedisClient(dataData)
	dispatchService := service.NewDispatchService(universalClient, dispatch, logger)
	database, cleanup2, err := provideMongoDB(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	metrics := provideMetrics()
	messageStorage, err := provideMessageStorage(database, logger, metrics)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kafkaConfig := provideKafkaConfig(confData)
	kafkaProducer := gateway.NewKafkaProducer(kafkaConfig, logger)
	messageService := service.NewMessageService(messageStorage, kafkaProducer, logger)
	string2 := provideNodeIDString()
	sessionManager := gateway.NewSessionManager(universalClient, string2)
	gatewayRegistryConfig := provideGatewayRegistryConfig(dispatch)
	userService := provideUserService(authUsecase, sessionManager, gatewayRegistryConfig)
	conversationRepo := data.NewConversationRepo(dataData, logger)
	conversationService := service.NewConversationService(conversationRepo)
	v := provideMetricsSlice(metrics)
	manager := gateway.NewManager(logger, v...)
	pushService := service.NewPushService(manager, logger)
	grpcServer := server.NewGRPCServer(confServer, authService, dispatchService, messageService, userService, conversationService, pushService, auth, logger)
	groupRepo := data.NewGroupRepo(dataData, logger)
	groupService := service.NewGroupService(groupRepo)
	fileService := service.NewFileService(database, logger)
	v2 := provideJWTSecret(auth)
	heartbeatConfig := provideHeartbeatConfig(gatewayConfig)
	handler := provideHandler(manager, sessionManager, kafkaProducer, messageStorage, v2, heartbeatConfig, gatewayConfig, groupRepo, logger, metrics)
	webSocketServer := provideWebSocketServer(handler, logger, heartbeatConfig, gatewayConfig)
	authRateLimiter := provideAuthRateLimiter(universalClient, logger)
	httpServer := server.NewHTTPServer(confServer, authService, dispatchService, messageService, userService, conversationService, groupService, fileService, webSocketServer, auth, gatewayConfig, authRateLimiter, logger, metrics)
	mainNodeID := provideNodeID()
	gatewayURL := provideGatewayURL(dispatch, mainNodeID)
	gatewayGrpcAddr := provideGatewayGrpcAddr(dispatch, confServer, mainNodeID)
	gatewayRegistry := provideGatewayRegistry(universalClient, mainNodeID, gatewayURL, gatewayGrpcAddr, gatewayRegistryConfig, manager, logger)
	app := newApp(logger, grpcServer, httpServer, gatewayRegistry, webSocketServer, heartbeatConfig)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

// provideKafkaConfig returns Kafka configuration from the config file, falling
// back to environment variables and sensible defaults. By default the producer
// operates synchronously (Async=false) so that Gateway only ACKs clients after
// Kafka has acknowledged the message.
func provideKafkaConfig(confData *conf.Data) gateway.KafkaConfig {
	var cfg gateway.KafkaConfig
	if confData != nil && confData.Kafka != nil {
		cfg = gateway.KafkaConfigFromProto(confData.Kafka)
	}

	if brokers := os.Getenv("KAFKA_BROKERS"); brokers != "" {
		cfg.Brokers = []string{brokers}
	}
	if topic := os.Getenv("KAFKA_TOPIC"); topic != "" {
		cfg.Topic = topic
	}

	if len(cfg.Brokers) == 0 {
		cfg.Brokers = []string{"127.0.0.1:9092"}
	}
	if cfg.Topic == "" {
		cfg.Topic = "im-messages"
	}
	if cfg.BatchSize == 0 {
		cfg.BatchSize = 100
	}
	return cfg
}

// provideNodeIDString returns the unique node ID as a plain string.
// This is used by gateway.SessionManager which expects a string.
func provideNodeIDString() string {
	nodeID2 := os.Getenv("GATEWAY_NODE_ID")
	if nodeID2 == "" {
		nodeID2 = id
	}
	if nodeID2 == "" {
		nodeID2, _ = os.Hostname()
	}
	if nodeID2 == "" {
		nodeID2 = "gateway-0"
	}
	return nodeID2
}

// NodeID is a unique identifier for a gateway node, used to disambiguate
// wire providers that would otherwise have the same type.
type NodeID string

// provideNodeID returns the unique node ID as a typed NodeID.
func provideNodeID() NodeID {
	return NodeID(provideNodeIDString())
}

// GatewayURL is the WebSocket endpoint advertised to clients.
type GatewayURL string

// provideGatewayURL derives the WebSocket URL from environment or config.
func provideGatewayURL(dispatchConf *conf.Dispatch, nodeID2 NodeID) GatewayURL {
	id2 := string(nodeID2)

	if dispatchConf != nil {
		for _, gw := range dispatchConf.Gateways {
			if gw.NodeId == id2 && gw.GatewayUrl != "" {
				return GatewayURL(gw.GatewayUrl)
			}
		}
		if len(dispatchConf.Gateways) > 0 && dispatchConf.Gateways[0].GatewayUrl != "" {
			return GatewayURL(dispatchConf.Gateways[0].GatewayUrl)
		}
	}

	wsAddr := os.Getenv("GATEWAY_WS_ADDR")
	if wsAddr == "" {
		wsAddr = "ws://localhost:8000/ws"
	}
	return GatewayURL(wsAddr)
}

// GatewayGrpcAddr is the gRPC endpoint advertised to other services (msgworker).
type GatewayGrpcAddr string

// provideGatewayGrpcAddr derives the gRPC address from environment or config.
func provideGatewayGrpcAddr(dispatchConf *conf.Dispatch, serverConf *conf.Server, nodeID2 NodeID) GatewayGrpcAddr {
	id2 := string(nodeID2)

	if dispatchConf != nil {
		for _, gw := range dispatchConf.Gateways {
			if gw.NodeId == id2 && gw.GetGatewayGrpcAddr() != "" {
				return GatewayGrpcAddr(gw.GetGatewayGrpcAddr())
			}
		}
		if len(dispatchConf.Gateways) > 0 && dispatchConf.Gateways[0].GetGatewayGrpcAddr() != "" {
			return GatewayGrpcAddr(dispatchConf.Gateways[0].GetGatewayGrpcAddr())
		}
	}

	grpcAddr := os.Getenv("GATEWAY_GRPC_ADDR")
	if grpcAddr == "" && serverConf != nil && serverConf.Grpc != nil && serverConf.Grpc.Addr != "" {
		grpcAddr = serverConf.Grpc.Addr
	}
	if grpcAddr == "" {
		grpcAddr = "127.0.0.1:9000"
	}
	return GatewayGrpcAddr(grpcAddr)
}

// GatewayRegistryConfig holds heartbeat configuration for the gateway registry.
type GatewayRegistryConfig struct {
	Interval time.Duration
	TTL      time.Duration
}

// provideGatewayRegistryConfig returns heartbeat interval and TTL from config or defaults.
func provideGatewayRegistryConfig(dispatchConf *conf.Dispatch) GatewayRegistryConfig {
	cfg := GatewayRegistryConfig{
		Interval: 10 * time.Second,
		TTL:      30 * time.Second,
	}
	if dispatchConf != nil {
		if dispatchConf.HeartbeatInterval != nil {
			cfg.Interval = dispatchConf.HeartbeatInterval.AsDuration()
		}
		if dispatchConf.NodeTtl != nil {
			cfg.TTL = dispatchConf.NodeTtl.AsDuration()
		}
	}
	return cfg
}

// provideJWTSecret extracts the JWT secret from auth config.
func provideJWTSecret(c *conf.Auth) []byte {
	return []byte(c.JwtSecret)
}

// provideHeartbeatConfig returns heartbeat configuration from config or defaults (#32).
func provideHeartbeatConfig(gatewayConf *conf.GatewayConfig) gateway.HeartbeatConfig {
	cfg := gateway.HeartbeatConfig{
		Interval: 30 * time.Second,
		Timeout:  90 * time.Second,
	}
	if gatewayConf != nil {
		if gatewayConf.HeartbeatInterval != nil {
			cfg.Interval = gatewayConf.HeartbeatInterval.AsDuration()
		}
		if gatewayConf.HeartbeatTimeout != nil {
			cfg.Timeout = gatewayConf.HeartbeatTimeout.AsDuration()
		}
		if gatewayConf.ReadTimeout != nil {
			cfg.ReadTimeout = gatewayConf.ReadTimeout.AsDuration()
		}
		if gatewayConf.WriteTimeout != nil {
			cfg.WriteTimeout = gatewayConf.WriteTimeout.AsDuration()
		}
	}
	return cfg
}

// provideRedisClient extracts the Redis client from Data.
func provideRedisClient(d *data.Data) redis.UniversalClient {
	return d.Redis
}

// provideMongoDB creates a MongoDB client and returns the database.
func provideMongoDB(c *conf.Data) (*mongo.Database, func(), error) {
	if c == nil || c.Mongodb == nil || c.Mongodb.Uri == "" {
		return nil, nil, fmt.Errorf("mongodb config is required")
	}
	client, err := mongo.Connect(options.Client().ApplyURI(c.Mongodb.Uri))
	if err != nil {
		return nil, nil, fmt.Errorf("connect mongodb: %w", err)
	}
	db := client.Database(c.Mongodb.Database)
	cleanup := func() {
		ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = client.Disconnect(ctx)
	}
	return db, cleanup, nil
}

// provideMessageStorage creates a MessageStorage from MongoDB database and ensures indexes.
func provideMessageStorage(db *mongo.Database, logger log.Logger, m *metrics.Metrics) (*msgworker.MessageStorage, error) {
	storage := msgworker.NewMessageStorage(db, logger, m)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := storage.EnsureIndexes(ctx); err != nil {
		return nil, fmt.Errorf("ensure mongodb indexes: %w", err)
	}
	return storage, nil
}

// provideMetrics creates a Prometheus metrics collector.
func provideMetrics() *metrics.Metrics {
	return metrics.NewMetrics()
}

// provideMetricsSlice wraps a single metrics collector into a slice so that
// Wire can satisfy constructors that accept variadic metrics arguments.
func provideMetricsSlice(m *metrics.Metrics) []*metrics.Metrics {
	return []*metrics.Metrics{m}
}

// provideWebSocketServer creates a WebSocket server with configurable timeouts and origin policy.
func provideWebSocketServer(handler *gateway.Handler, logger log.Logger, hb gateway.HeartbeatConfig, gatewayConf *conf.GatewayConfig) *gateway.WebSocketServer {
	allowedOrigins := []string(nil)
	if gatewayConf != nil {
		allowedOrigins = gatewayConf.AllowedOrigins
	}
	return gateway.NewWebSocketServer(handler, logger, hb.ReadTimeout, hb.WriteTimeout, allowedOrigins)
}

// provideHandler centralizes runtime-only gateway options so wire_gen.go stays generated.
func provideHandler(manager *gateway.Manager, sessions *gateway.SessionManager, producer gateway.MessageProducer, storage *msgworker.MessageStorage, jwtSecret []byte, hb gateway.HeartbeatConfig, gatewayConf *conf.GatewayConfig, groups data.GroupRepo, logger log.Logger, m *metrics.Metrics) *gateway.Handler {
	h := gateway.NewHandler(manager, sessions, producer, storage, jwtSecret, hb, logger, m)
	if gatewayConf != nil && gatewayConf.RecallWindow != nil {
		h.SetRecallWindow(gatewayConf.RecallWindow.AsDuration())
	}
	if gatewayConf != nil && gatewayConf.MsgRateLimit != nil {
		h.SetMessageRateLimit(gatewayConf.MsgRateLimit.MsgPerSec, int(gatewayConf.MsgRateLimit.Burst))
	}
	h.SetGroupMemberResolver(func(ctx context.Context, groupID string) ([]int64, error) {
		members, err := groups.ListMembers(ctx, groupID)
		if err != nil {
			return nil, err
		}
		ids := make([]int64, 0, len(members))
		for _, member := range members {
			ids = append(ids, member.UserId)
		}
		return ids, nil
	})
	return h
}

// provideAuthRateLimiter builds the auth-endpoint rate limiter on the
// shared Redis client. A missing Redis client yields a disabled limiter
// (Allow always true) so auth never hard-fails on infra misconfiguration.
func provideAuthRateLimiter(r redis.UniversalClient, logger log.Logger) *server.AuthRateLimiter {
	return server.NewAuthRateLimiter(r, logger)
}

type sessionPresenceChecker struct {
	sessions *gateway.SessionManager
	nodeTTL  time.Duration
}

func (p *sessionPresenceChecker) IsUserOnline(ctx context.Context, userID int64) (bool, error) {
	return p.sessions.IsUserOnline(ctx, userID, p.nodeTTL)
}

func provideUserService(uc *biz.AuthUsecase, sessions *gateway.SessionManager, cfg GatewayRegistryConfig) *service.UserService {
	svc := service.NewUserService(uc)
	svc.SetPresenceChecker(&sessionPresenceChecker{sessions: sessions, nodeTTL: cfg.TTL})
	return svc
}

// provideGatewayRegistry creates a GatewayRegistry for node heartbeat registration.
func provideGatewayRegistry(redis2 redis.UniversalClient, nodeID2 NodeID, url GatewayURL, grpcAddr GatewayGrpcAddr, cfg GatewayRegistryConfig, manager *gateway.Manager, logger log.Logger) *gateway.GatewayRegistry {
	return gateway.NewGatewayRegistry(redis2, string(nodeID2), string(url), string(grpcAddr), cfg.Interval, cfg.TTL, manager, logger)
}
