// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: im/v1/conversation.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_im_v1_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *ListConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConversationsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Conversation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Topic          string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                    // p2p / group
	PeerId         int64                  `protobuf:"varint,3,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"` // P2P counterpart user_id
	PeerUsername   string                 `protobuf:"bytes,4,opt,name=peer_username,json=peerUsername,proto3" json:"peer_username,omitempty"`
	LastMsgPreview string                 `protobuf:"bytes,5,opt,name=last_msg_preview,json=lastMsgPreview,proto3" json:"last_msg_preview,omitempty"`
	LastMsgAt      int64                  `protobuf:"varint,6,opt,name=last_msg_at,json=lastMsgAt,proto3" json:"last_msg_at,omitempty"`
	LastSeq        uint64                 `protobuf:"varint,7,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	LastReadSeq    uint64                 `protobuf:"varint,8,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	UnreadCount    int32                  `protobuf:"varint,9,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_im_v1_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_im_v1_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *Conversation) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Conversation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Conversation) GetPeerId() int64 {
	if x != nil {
		return x.PeerId
	}
	return 0
}

func (x *Conversation) GetPeerUsername() string {
	if x != nil {
		return x.PeerUsername
	}
	return ""
}

func (x *Conversation) GetLastMsgPreview() string {
	if x != nil {
		return x.LastMsgPreview
	}
	return ""
}

func (x *Conversation) GetLastMsgAt() int64 {
	if x != nil {
		return x.LastMsgAt
	}
	return 0
}

func (x *Conversation) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *Conversation) GetLastReadSeq() uint64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *Conversation) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type ListConversationsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsReply) Reset() {
	*x = ListConversationsReply{}
	mi := &file_im_v1_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsReply) ProtoMessage() {}

func (x *ListConversationsReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsReply.ProtoReflect.Descriptor instead.
func (*ListConversationsReply) Descriptor() ([]byte, []int) {
	return file_im_v1_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *ListConversationsReply) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListConversationsReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type MarkConversationReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkConversationReadRequest) Reset() {
	*x = MarkConversationReadRequest{}
	mi := &file_im_v1_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkConversationReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkConversationReadRequest) ProtoMessage() {}

func (x *MarkConversationReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkConversationReadRequest.ProtoReflect.Descriptor instead.
func (*MarkConversationReadRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *MarkConversationReadRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

var File_im_v1_conversation_proto protoreflect.FileDescriptor

const file_im_v1_conversation_proto_rawDesc = "" +
	"\n" +
	"\x18im/v1/conversation.proto\x12\tapi.im.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"H\n" +
	"\x18ListConversationsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"\xa2\x02\n" +
	"\fConversation\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\apeer_id\x18\x03 \x01(\x03R\x06peerId\x12#\n" +
	"\rpeer_username\x18\x04 \x01(\tR\fpeerUsername\x12(\n" +
	"\x10last_msg_preview\x18\x05 \x01(\tR\x0elastMsgPreview\x12\x1e\n" +
	"\vlast_msg_at\x18\x06 \x01(\x03R\tlastMsgAt\x12\x19\n" +
	"\blast_seq\x18\a \x01(\x04R\alastSeq\x12\"\n" +
	"\rlast_read_seq\x18\b \x01(\x04R\vlastReadSeq\x12!\n" +
	"\funread_count\x18\t \x01(\x05R\vunreadCount\"r\n" +
	"\x16ListConversationsReply\x12=\n" +
	"\rconversations\x18\x01 \x03(\v2\x17.api.im.v1.ConversationR\rconversations\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"3\n" +
	"\x1bMarkConversationReadRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic2\x91\x02\n" +
	"\x13ConversationService\x12v\n" +
	"\x11ListConversations\x12#.api.im.v1.ListConversationsRequest\x1a!.api.im.v1.ListConversationsReply\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/conversations\x12\x81\x01\n" +
	"\x14MarkConversationRead\x12&.api.im.v1.MarkConversationReadRequest\x1a\x16.google.protobuf.Empty\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/conversations/{topic}/readB\x18Z\x16nonoka-im/api/im/v1;v1b\x06proto3"

var (
	file_im_v1_conversation_proto_rawDescOnce sync.Once
	file_im_v1_conversation_proto_rawDescData []byte
)

func file_im_v1_conversation_proto_rawDescGZIP() []byte {
	file_im_v1_conversation_proto_rawDescOnce.Do(func() {
		file_im_v1_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_v1_conversation_proto_rawDesc), len(file_im_v1_conversation_proto_rawDesc)))
	})
	return file_im_v1_conversation_proto_rawDescData
}

var file_im_v1_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_im_v1_conversation_proto_goTypes = []any{
	(*ListConversationsRequest)(nil),    // 0: api.im.v1.ListConversationsRequest
	(*Conversation)(nil),                // 1: api.im.v1.Conversation
	(*ListConversationsReply)(nil),      // 2: api.im.v1.ListConversationsReply
	(*MarkConversationReadRequest)(nil), // 3: api.im.v1.MarkConversationReadRequest
	(*emptypb.Empty)(nil),               // 4: google.protobuf.Empty
}
var file_im_v1_conversation_proto_depIdxs = []int32{
	1, // 0: api.im.v1.ListConversationsReply.conversations:type_name -> api.im.v1.Conversation
	0, // 1: api.im.v1.ConversationService.ListConversations:input_type -> api.im.v1.ListConversationsRequest
	3, // 2: api.im.v1.ConversationService.MarkConversationRead:input_type -> api.im.v1.MarkConversationReadRequest
	2, // 3: api.im.v1.ConversationService.ListConversations:output_type -> api.im.v1.ListConversationsReply
	4, // 4: api.im.v1.ConversationService.MarkConversationRead:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_im_v1_conversation_proto_init() }
func file_im_v1_conversation_proto_init() {
	if File_im_v1_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_v1_conversation_proto_rawDesc), len(file_im_v1_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_v1_conversation_proto_goTypes,
		DependencyIndexes: file_im_v1_conversation_proto_depIdxs,
		MessageInfos:      file_im_v1_conversation_proto_msgTypes,
	}.Build()
	File_im_v1_conversation_proto = out.File
	file_im_v1_conversation_proto_goTypes = nil
	file_im_v1_conversation_proto_depIdxs = nil
}
