// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.3
// source: im/v1/conversation.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationConversationServiceListConversations = "/api.im.v1.ConversationService/ListConversations"
const OperationConversationServiceMarkConversationRead = "/api.im.v1.ConversationService/MarkConversationRead"

type ConversationServiceHTTPServer interface {
	ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsReply, error)
	MarkConversationRead(context.Context, *MarkConversationReadRequest) (*emptypb.Empty, error)
}

func RegisterConversationServiceHTTPServer(s *http.Server, srv ConversationServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/conversations", _ConversationService_ListConversations0_HTTP_Handler(srv))
	r.POST("/v1/conversations/{topic}/read", _ConversationService_MarkConversationRead0_HTTP_Handler(srv))
}

func _ConversationService_ListConversations0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListConversationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceListConversations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListConversations(ctx, req.(*ListConversationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListConversationsReply)
		return ctx.Result(200, reply)
	}
}

func _ConversationService_MarkConversationRead0_HTTP_Handler(srv ConversationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in MarkConversationReadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationConversationServiceMarkConversationRead)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkConversationRead(ctx, req.(*MarkConversationReadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type ConversationServiceHTTPClient interface {
	ListConversations(ctx context.Context, req *ListConversationsRequest, opts ...http.CallOption) (rsp *ListConversationsReply, err error)
	MarkConversationRead(ctx context.Context, req *MarkConversationReadRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type ConversationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewConversationServiceHTTPClient(client *http.Client) ConversationServiceHTTPClient {
	return &ConversationServiceHTTPClientImpl{client}
}

func (c *ConversationServiceHTTPClientImpl) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...http.CallOption) (*ListConversationsReply, error) {
	var out ListConversationsReply
	pattern := "/v1/conversations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationConversationServiceListConversations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ConversationServiceHTTPClientImpl) MarkConversationRead(ctx context.Context, in *MarkConversationReadRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/conversations/{topic}/read"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationConversationServiceMarkConversationRead))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
