// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.3
// source: im/v1/dispatch.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDispatchServiceGateway = "/api.im.v1.DispatchService/Gateway"

type DispatchServiceHTTPServer interface {
	Gateway(context.Context, *GetGatewayRequest) (*GetGatewayReply, error)
}

func RegisterDispatchServiceHTTPServer(s *http.Server, srv DispatchServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/dispatch/gateway", _DispatchService_Gateway0_HTTP_Handler(srv))
}

func _DispatchService_Gateway0_HTTP_Handler(srv DispatchServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGatewayRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDispatchServiceGateway)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Gateway(ctx, req.(*GetGatewayRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGatewayReply)
		return ctx.Result(200, reply)
	}
}

type DispatchServiceHTTPClient interface {
	Gateway(ctx context.Context, req *GetGatewayRequest, opts ...http.CallOption) (rsp *GetGatewayReply, err error)
}

type DispatchServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDispatchServiceHTTPClient(client *http.Client) DispatchServiceHTTPClient {
	return &DispatchServiceHTTPClientImpl{client}
}

func (c *DispatchServiceHTTPClientImpl) Gateway(ctx context.Context, in *GetGatewayRequest, opts ...http.CallOption) (*GetGatewayReply, error) {
	var out GetGatewayReply
	pattern := "/v1/dispatch/gateway"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDispatchServiceGateway))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
