// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: im/v1/dispatch.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGatewayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // optional: for consistent hashing dispatch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayRequest) Reset() {
	*x = GetGatewayRequest{}
	mi := &file_im_v1_dispatch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayRequest) ProtoMessage() {}

func (x *GetGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_dispatch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_dispatch_proto_rawDescGZIP(), []int{0}
}

func (x *GetGatewayRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetGatewayReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayUrl    string                 `protobuf:"bytes,1,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"` // e.g. "ws://192.168.1.10:8080/ws"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayReply) Reset() {
	*x = GetGatewayReply{}
	mi := &file_im_v1_dispatch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayReply) ProtoMessage() {}

func (x *GetGatewayReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_dispatch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayReply.ProtoReflect.Descriptor instead.
func (*GetGatewayReply) Descriptor() ([]byte, []int) {
	return file_im_v1_dispatch_proto_rawDescGZIP(), []int{1}
}

func (x *GetGatewayReply) GetGatewayUrl() string {
	if x != nil {
		return x.GatewayUrl
	}
	return ""
}

var File_im_v1_dispatch_proto protoreflect.FileDescriptor

const file_im_v1_dispatch_proto_rawDesc = "" +
	"\n" +
	"\x14im/v1/dispatch.proto\x12\tapi.im.v1\x1a\x1cgoogle/api/annotations.proto\",\n" +
	"\x11GetGatewayRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"2\n" +
	"\x0fGetGatewayReply\x12\x1f\n" +
	"\vgateway_url\x18\x01 \x01(\tR\n" +
	"gatewayUrl2t\n" +
	"\x0fDispatchService\x12a\n" +
	"\aGateway\x12\x1c.api.im.v1.GetGatewayRequest\x1a\x1a.api.im.v1.GetGatewayReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/dispatch/gatewayB\x18Z\x16nonoka-im/api/im/v1;v1b\x06proto3"

var (
	file_im_v1_dispatch_proto_rawDescOnce sync.Once
	file_im_v1_dispatch_proto_rawDescData []byte
)

func file_im_v1_dispatch_proto_rawDescGZIP() []byte {
	file_im_v1_dispatch_proto_rawDescOnce.Do(func() {
		file_im_v1_dispatch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_v1_dispatch_proto_rawDesc), len(file_im_v1_dispatch_proto_rawDesc)))
	})
	return file_im_v1_dispatch_proto_rawDescData
}

var file_im_v1_dispatch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_im_v1_dispatch_proto_goTypes = []any{
	(*GetGatewayRequest)(nil), // 0: api.im.v1.GetGatewayRequest
	(*GetGatewayReply)(nil),   // 1: api.im.v1.GetGatewayReply
}
var file_im_v1_dispatch_proto_depIdxs = []int32{
	0, // 0: api.im.v1.DispatchService.Gateway:input_type -> api.im.v1.GetGatewayRequest
	1, // 1: api.im.v1.DispatchService.Gateway:output_type -> api.im.v1.GetGatewayReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_im_v1_dispatch_proto_init() }
func file_im_v1_dispatch_proto_init() {
	if File_im_v1_dispatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_v1_dispatch_proto_rawDesc), len(file_im_v1_dispatch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_v1_dispatch_proto_goTypes,
		DependencyIndexes: file_im_v1_dispatch_proto_depIdxs,
		MessageInfos:      file_im_v1_dispatch_proto_msgTypes,
	}.Build()
	File_im_v1_dispatch_proto = out.File
	file_im_v1_dispatch_proto_goTypes = nil
	file_im_v1_dispatch_proto_depIdxs = nil
}
