// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v4.25.3
// source: im/v1/group.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGroupServiceAddGroupMember = "/api.im.v1.GroupService/AddGroupMember"
const OperationGroupServiceCreateGroup = "/api.im.v1.GroupService/CreateGroup"
const OperationGroupServiceGetGroup = "/api.im.v1.GroupService/GetGroup"
const OperationGroupServiceListGroupMembers = "/api.im.v1.GroupService/ListGroupMembers"
const OperationGroupServiceListMyGroups = "/api.im.v1.GroupService/ListMyGroups"
const OperationGroupServiceRemoveGroupMember = "/api.im.v1.GroupService/RemoveGroupMember"

type GroupServiceHTTPServer interface {
	// AddGroupMember AddGroupMember adds a user to a group.
	AddGroupMember(context.Context, *AddGroupMemberRequest) (*emptypb.Empty, error)
	// CreateGroup CreateGroup creates a new group and adds the creator plus optional members.
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupReply, error)
	// GetGroup GetGroup returns details of a specific group.
	GetGroup(context.Context, *GetGroupRequest) (*Group, error)
	// ListGroupMembers ListGroupMembers returns the members of a group.
	ListGroupMembers(context.Context, *ListGroupMembersRequest) (*ListGroupMembersReply, error)
	// ListMyGroups ListMyGroups returns all groups the authenticated user is a member of.
	ListMyGroups(context.Context, *emptypb.Empty) (*ListGroupsReply, error)
	// RemoveGroupMember RemoveGroupMember removes a user from a group.
	RemoveGroupMember(context.Context, *RemoveGroupMemberRequest) (*emptypb.Empty, error)
}

func RegisterGroupServiceHTTPServer(s *http.Server, srv GroupServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/groups", _GroupService_CreateGroup0_HTTP_Handler(srv))
	r.GET("/v1/groups", _GroupService_ListMyGroups0_HTTP_Handler(srv))
	r.GET("/v1/groups/{group_id}", _GroupService_GetGroup0_HTTP_Handler(srv))
	r.POST("/v1/groups/{group_id}/members", _GroupService_AddGroupMember0_HTTP_Handler(srv))
	r.DELETE("/v1/groups/{group_id}/members/{user_id}", _GroupService_RemoveGroupMember0_HTTP_Handler(srv))
	r.GET("/v1/groups/{group_id}/members", _GroupService_ListGroupMembers0_HTTP_Handler(srv))
}

func _GroupService_CreateGroup0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateGroupRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceCreateGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateGroup(ctx, req.(*CreateGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateGroupReply)
		return ctx.Result(200, reply)
	}
}

func _GroupService_ListMyGroups0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceListMyGroups)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMyGroups(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGroupsReply)
		return ctx.Result(200, reply)
	}
}

func _GroupService_GetGroup0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceGetGroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGroup(ctx, req.(*GetGroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Group)
		return ctx.Result(200, reply)
	}
}

func _GroupService_AddGroupMember0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddGroupMemberRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceAddGroupMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddGroupMember(ctx, req.(*AddGroupMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _GroupService_RemoveGroupMember0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveGroupMemberRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceRemoveGroupMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveGroupMember(ctx, req.(*RemoveGroupMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _GroupService_ListGroupMembers0_HTTP_Handler(srv GroupServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGroupMembersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGroupServiceListGroupMembers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGroupMembers(ctx, req.(*ListGroupMembersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGroupMembersReply)
		return ctx.Result(200, reply)
	}
}

type GroupServiceHTTPClient interface {
	// AddGroupMember AddGroupMember adds a user to a group.
	AddGroupMember(ctx context.Context, req *AddGroupMemberRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// CreateGroup CreateGroup creates a new group and adds the creator plus optional members.
	CreateGroup(ctx context.Context, req *CreateGroupRequest, opts ...http.CallOption) (rsp *CreateGroupReply, err error)
	// GetGroup GetGroup returns details of a specific group.
	GetGroup(ctx context.Context, req *GetGroupRequest, opts ...http.CallOption) (rsp *Group, err error)
	// ListGroupMembers ListGroupMembers returns the members of a group.
	ListGroupMembers(ctx context.Context, req *ListGroupMembersRequest, opts ...http.CallOption) (rsp *ListGroupMembersReply, err error)
	// ListMyGroups ListMyGroups returns all groups the authenticated user is a member of.
	ListMyGroups(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListGroupsReply, err error)
	// RemoveGroupMember RemoveGroupMember removes a user from a group.
	RemoveGroupMember(ctx context.Context, req *RemoveGroupMemberRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type GroupServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewGroupServiceHTTPClient(client *http.Client) GroupServiceHTTPClient {
	return &GroupServiceHTTPClientImpl{client}
}

// AddGroupMember AddGroupMember adds a user to a group.
func (c *GroupServiceHTTPClientImpl) AddGroupMember(ctx context.Context, in *AddGroupMemberRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/groups/{group_id}/members"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGroupServiceAddGroupMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateGroup CreateGroup creates a new group and adds the creator plus optional members.
func (c *GroupServiceHTTPClientImpl) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...http.CallOption) (*CreateGroupReply, error) {
	var out CreateGroupReply
	pattern := "/v1/groups"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGroupServiceCreateGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetGroup GetGroup returns details of a specific group.
func (c *GroupServiceHTTPClientImpl) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...http.CallOption) (*Group, error) {
	var out Group
	pattern := "/v1/groups/{group_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGroupServiceGetGroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListGroupMembers ListGroupMembers returns the members of a group.
func (c *GroupServiceHTTPClientImpl) ListGroupMembers(ctx context.Context, in *ListGroupMembersRequest, opts ...http.CallOption) (*ListGroupMembersReply, error) {
	var out ListGroupMembersReply
	pattern := "/v1/groups/{group_id}/members"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGroupServiceListGroupMembers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListMyGroups ListMyGroups returns all groups the authenticated user is a member of.
func (c *GroupServiceHTTPClientImpl) ListMyGroups(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListGroupsReply, error) {
	var out ListGroupsReply
	pattern := "/v1/groups"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGroupServiceListMyGroups))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveGroupMember RemoveGroupMember removes a user from a group.
func (c *GroupServiceHTTPClientImpl) RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/groups/{group_id}/members/{user_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGroupServiceRemoveGroupMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
