// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: im/v1/group.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MemberIds     []int64                `protobuf:"varint,2,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_im_v1_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_group_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateGroupReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupReply) Reset() {
	*x = CreateGroupReply{}
	mi := &file_im_v1_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupReply) ProtoMessage() {}

func (x *CreateGroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupReply.ProtoReflect.Descriptor instead.
func (*CreateGroupReply) Descriptor() ([]byte, []int) {
	return file_im_v1_group_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupReply) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CreateGroupReply) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OwnerId       int64                  `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_im_v1_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_im_v1_group_proto_rawDescGZIP(), []int{2}
}

func (x *Group) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Group) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Group) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type ListGroupsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsReply) Reset() {
	*x = ListGroupsReply{}
	mi := &file_im_v1_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsReply) ProtoMessage() {}

func (x *ListGroupsReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsReply.ProtoReflect.Descriptor instead.
func (*ListGroupsReply) Descriptor() ([]byte, []int) {
	return file_im_v1_group_proto_rawDescGZIP(), []int{3}
}

func (x *ListGroupsReply) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GetGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupRequest) Reset() {
	*x = GetGroupRequest{}
	mi := &file_im_v1_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupRequest) ProtoMessage() {}

func (x *GetGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupRequest.ProtoReflect.Descriptor instead.
func (*GetGroupRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_group_proto_rawDescGZIP(), []int{4}
}

func (x *GetGroupRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type AddGroupMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupMemberRequest) Reset() {
	*x = AddGroupMemberRequest{}
	mi := &file_im_v1_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupMemberRequest) ProtoMessage() {}

func (x *AddGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*AddGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_group_proto_rawDescGZIP(), []int{5}
}

func (x *AddGroupMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddGroupMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RemoveGroupMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveGroupMemberRequest) Reset() {
	*x = RemoveGroupMemberRequest{}
	mi := &file_im_v1_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveGroupMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGroupMemberRequest) ProtoMessage() {}

func (x *RemoveGroupMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGroupMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveGroupMemberRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_group_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveGroupMemberRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemoveGroupMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListGroupMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersRequest) Reset() {
	*x = ListGroupMembersRequest{}
	mi := &file_im_v1_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersRequest) ProtoMessage() {}

func (x *ListGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*ListGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_group_proto_rawDescGZIP(), []int{7}
}

func (x *ListGroupMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_im_v1_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_im_v1_group_proto_rawDescGZIP(), []int{8}
}

func (x *GroupMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMember) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ListGroupMembersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*GroupMember         `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersReply) Reset() {
	*x = ListGroupMembersReply{}
	mi := &file_im_v1_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersReply) ProtoMessage() {}

func (x *ListGroupMembersReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersReply.ProtoReflect.Descriptor instead.
func (*ListGroupMembersReply) Descriptor() ([]byte, []int) {
	return file_im_v1_group_proto_rawDescGZIP(), []int{9}
}

func (x *ListGroupMembersReply) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_im_v1_group_proto protoreflect.FileDescriptor

const file_im_v1_group_proto_rawDesc = "" +
	"\n" +
	"\x11im/v1/group.proto\x12\tapi.im.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"G\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\x03R\tmemberIds\"C\n" +
	"\x10CreateGroupReply\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\x86\x01\n" +
	"\x05Group\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x03R\aownerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\";\n" +
	"\x0fListGroupsReply\x12(\n" +
	"\x06groups\x18\x01 \x03(\v2\x10.api.im.v1.GroupR\x06groups\",\n" +
	"\x0fGetGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"K\n" +
	"\x15AddGroupMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"N\n" +
	"\x18RemoveGroupMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"4\n" +
	"\x17ListGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"B\n" +
	"\vGroupMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"I\n" +
	"\x15ListGroupMembersReply\x120\n" +
	"\amembers\x18\x01 \x03(\v2\x16.api.im.v1.GroupMemberR\amembers2\x9c\x05\n" +
	"\fGroupService\x12`\n" +
	"\vCreateGroup\x12\x1d.api.im.v1.CreateGroupRequest\x1a\x1b.api.im.v1.CreateGroupReply\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/groups\x12V\n" +
	"\fListMyGroups\x12\x16.google.protobuf.Empty\x1a\x1a.api.im.v1.ListGroupsReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/groups\x12W\n" +
	"\bGetGroup\x12\x1a.api.im.v1.GetGroupRequest\x1a\x10.api.im.v1.Group\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/groups/{group_id}\x12t\n" +
	"\x0eAddGroupMember\x12 .api.im.v1.AddGroupMemberRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/groups/{group_id}/members\x12\x81\x01\n" +
	"\x11RemoveGroupMember\x12#.api.im.v1.RemoveGroupMemberRequest\x1a\x16.google.protobuf.Empty\"/\x82\xd3\xe4\x93\x02)*'/v1/groups/{group_id}/members/{user_id}\x12\x7f\n" +
	"\x10ListGroupMembers\x12\".api.im.v1.ListGroupMembersRequest\x1a .api.im.v1.ListGroupMembersReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/groups/{group_id}/membersB\x18Z\x16nonoka-im/api/im/v1;v1b\x06proto3"

var (
	file_im_v1_group_proto_rawDescOnce sync.Once
	file_im_v1_group_proto_rawDescData []byte
)

func file_im_v1_group_proto_rawDescGZIP() []byte {
	file_im_v1_group_proto_rawDescOnce.Do(func() {
		file_im_v1_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_v1_group_proto_rawDesc), len(file_im_v1_group_proto_rawDesc)))
	})
	return file_im_v1_group_proto_rawDescData
}

var file_im_v1_group_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_im_v1_group_proto_goTypes = []any{
	(*CreateGroupRequest)(nil),       // 0: api.im.v1.CreateGroupRequest
	(*CreateGroupReply)(nil),         // 1: api.im.v1.CreateGroupReply
	(*Group)(nil),                    // 2: api.im.v1.Group
	(*ListGroupsReply)(nil),          // 3: api.im.v1.ListGroupsReply
	(*GetGroupRequest)(nil),          // 4: api.im.v1.GetGroupRequest
	(*AddGroupMemberRequest)(nil),    // 5: api.im.v1.AddGroupMemberRequest
	(*RemoveGroupMemberRequest)(nil), // 6: api.im.v1.RemoveGroupMemberRequest
	(*ListGroupMembersRequest)(nil),  // 7: api.im.v1.ListGroupMembersRequest
	(*GroupMember)(nil),              // 8: api.im.v1.GroupMember
	(*ListGroupMembersReply)(nil),    // 9: api.im.v1.ListGroupMembersReply
	(*emptypb.Empty)(nil),            // 10: google.protobuf.Empty
}
var file_im_v1_group_proto_depIdxs = []int32{
	2,  // 0: api.im.v1.ListGroupsReply.groups:type_name -> api.im.v1.Group
	8,  // 1: api.im.v1.ListGroupMembersReply.members:type_name -> api.im.v1.GroupMember
	0,  // 2: api.im.v1.GroupService.CreateGroup:input_type -> api.im.v1.CreateGroupRequest
	10, // 3: api.im.v1.GroupService.ListMyGroups:input_type -> google.protobuf.Empty
	4,  // 4: api.im.v1.GroupService.GetGroup:input_type -> api.im.v1.GetGroupRequest
	5,  // 5: api.im.v1.GroupService.AddGroupMember:input_type -> api.im.v1.AddGroupMemberRequest
	6,  // 6: api.im.v1.GroupService.RemoveGroupMember:input_type -> api.im.v1.RemoveGroupMemberRequest
	7,  // 7: api.im.v1.GroupService.ListGroupMembers:input_type -> api.im.v1.ListGroupMembersRequest
	1,  // 8: api.im.v1.GroupService.CreateGroup:output_type -> api.im.v1.CreateGroupReply
	3,  // 9: api.im.v1.GroupService.ListMyGroups:output_type -> api.im.v1.ListGroupsReply
	2,  // 10: api.im.v1.GroupService.GetGroup:output_type -> api.im.v1.Group
	10, // 11: api.im.v1.GroupService.AddGroupMember:output_type -> google.protobuf.Empty
	10, // 12: api.im.v1.GroupService.RemoveGroupMember:output_type -> google.protobuf.Empty
	9,  // 13: api.im.v1.GroupService.ListGroupMembers:output_type -> api.im.v1.ListGroupMembersReply
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_im_v1_group_proto_init() }
func file_im_v1_group_proto_init() {
	if File_im_v1_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_v1_group_proto_rawDesc), len(file_im_v1_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_v1_group_proto_goTypes,
		DependencyIndexes: file_im_v1_group_proto_depIdxs,
		MessageInfos:      file_im_v1_group_proto_msgTypes,
	}.Build()
	File_im_v1_group_proto = out.File
	file_im_v1_group_proto_goTypes = nil
	file_im_v1_group_proto_depIdxs = nil
}
