// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: im/v1/message.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_MSG_TYPE_UNSPECIFIED MsgType = 0
	MsgType_MSG_TYPE_TEXT        MsgType = 1
	MsgType_MSG_TYPE_IMAGE       MsgType = 2
	MsgType_MSG_TYPE_FILE        MsgType = 3
	MsgType_MSG_TYPE_VOICE       MsgType = 4
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_TYPE_UNSPECIFIED",
		1: "MSG_TYPE_TEXT",
		2: "MSG_TYPE_IMAGE",
		3: "MSG_TYPE_FILE",
		4: "MSG_TYPE_VOICE",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_UNSPECIFIED": 0,
		"MSG_TYPE_TEXT":        1,
		"MSG_TYPE_IMAGE":       2,
		"MSG_TYPE_FILE":        3,
		"MSG_TYPE_VOICE":       4,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_v1_message_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_im_v1_message_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{0}
}

// Client-to-server request
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	MsgType       MsgType                `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3,enum=api.im.v1.MsgType" json:"msg_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,4,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_im_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SendMessageRequest) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MSG_TYPE_UNSPECIFIED
}

func (x *SendMessageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendMessageRequest) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

// ACK
type SendMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	MsgId         int64                  `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TopicSeq      uint64                 `protobuf:"varint,4,opt,name=topic_seq,json=topicSeq,proto3" json:"topic_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_im_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageReply) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessageReply) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendMessageReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SendMessageReply) GetTopicSeq() uint64 {
	if x != nil {
		return x.TopicSeq
	}
	return 0
}

// Push
type MessagePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TopicSeq      uint64                 `protobuf:"varint,7,opt,name=topic_seq,json=topicSeq,proto3" json:"topic_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePush) Reset() {
	*x = MessagePush{}
	mi := &file_im_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePush) ProtoMessage() {}

func (x *MessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePush.ProtoReflect.Descriptor instead.
func (*MessagePush) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessagePush) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessagePush) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MessagePush) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessagePush) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MessagePush) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessagePush) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessagePush) GetTopicSeq() uint64 {
	if x != nil {
		return x.TopicSeq
	}
	return 0
}

// UpstreamMessage is sent from the Gateway to Kafka.
// MsgWorker consumes these messages to persist and dispatch them.
type UpstreamMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	MsgType       int32                  `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,5,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamMessage) Reset() {
	*x = UpstreamMessage{}
	mi := &file_im_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamMessage) ProtoMessage() {}

func (x *UpstreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamMessage.ProtoReflect.Descriptor instead.
func (*UpstreamMessage) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *UpstreamMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *UpstreamMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *UpstreamMessage) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *UpstreamMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpstreamMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *UpstreamMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_im_v1_message_proto protoreflect.FileDescriptor

const file_im_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x13im/v1/message.proto\x12\tapi.im.v1\x1a\x1cgoogle/api/annotations.proto\"\x97\x01\n" +
	"\x12SendMessageRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12-\n" +
	"\bmsg_type\x18\x02 \x01(\x0e2\x12.api.im.v1.MsgTypeR\amsgType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x04 \x01(\tR\vclientMsgId\"\x88\x01\n" +
	"\x10SendMessageReply\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\x03R\x05msgId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\ttopic_seq\x18\x04 \x01(\x04R\btopicSeq\"\xc7\x01\n" +
	"\vMessagePush\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x19\n" +
	"\bmsg_type\x18\x04 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\ttopic_seq\x18\a \x01(\x04R\btopicSeq\"\xbb\x01\n" +
	"\x0fUpstreamMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x19\n" +
	"\bmsg_type\x18\x03 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x05 \x01(\tR\vclientMsgId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp*q\n" +
	"\aMsgType\x12\x18\n" +
	"\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMSG_TYPE_TEXT\x10\x01\x12\x12\n" +
	"\x0eMSG_TYPE_IMAGE\x10\x02\x12\x11\n" +
	"\rMSG_TYPE_FILE\x10\x03\x12\x12\n" +
	"\x0eMSG_TYPE_VOICE\x10\x042x\n" +
	"\x0eMessageService\x12f\n" +
	"\vSendMessage\x12\x1d.api.im.v1.SendMessageRequest\x1a\x1b.api.im.v1.SendMessageReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/message/sendB\x18Z\x16nonoka-im/api/im/v1;v1b\x06proto3"

var (
	file_im_v1_message_proto_rawDescOnce sync.Once
	file_im_v1_message_proto_rawDescData []byte
)

func file_im_v1_message_proto_rawDescGZIP() []byte {
	file_im_v1_message_proto_rawDescOnce.Do(func() {
		file_im_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_v1_message_proto_rawDesc), len(file_im_v1_message_proto_rawDesc)))
	})
	return file_im_v1_message_proto_rawDescData
}

var file_im_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_im_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_im_v1_message_proto_goTypes = []any{
	(MsgType)(0),               // 0: api.im.v1.MsgType
	(*SendMessageRequest)(nil), // 1: api.im.v1.SendMessageRequest
	(*SendMessageReply)(nil),   // 2: api.im.v1.SendMessageReply
	(*MessagePush)(nil),        // 3: api.im.v1.MessagePush
	(*UpstreamMessage)(nil),    // 4: api.im.v1.UpstreamMessage
}
var file_im_v1_message_proto_depIdxs = []int32{
	0, // 0: api.im.v1.SendMessageRequest.msg_type:type_name -> api.im.v1.MsgType
	1, // 1: api.im.v1.MessageService.SendMessage:input_type -> api.im.v1.SendMessageRequest
	2, // 2: api.im.v1.MessageService.SendMessage:output_type -> api.im.v1.SendMessageReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_im_v1_message_proto_init() }
func file_im_v1_message_proto_init() {
	if File_im_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_v1_message_proto_rawDesc), len(file_im_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_v1_message_proto_goTypes,
		DependencyIndexes: file_im_v1_message_proto_depIdxs,
		EnumInfos:         file_im_v1_message_proto_enumTypes,
		MessageInfos:      file_im_v1_message_proto_msgTypes,
	}.Build()
	File_im_v1_message_proto = out.File
	file_im_v1_message_proto_goTypes = nil
	file_im_v1_message_proto_depIdxs = nil
}
