// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: im/v1/message.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_MSG_TYPE_UNSPECIFIED MsgType = 0
	MsgType_MSG_TYPE_TEXT        MsgType = 1
	MsgType_MSG_TYPE_IMAGE       MsgType = 2
	MsgType_MSG_TYPE_FILE        MsgType = 3
	MsgType_MSG_TYPE_VOICE       MsgType = 4
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "MSG_TYPE_UNSPECIFIED",
		1: "MSG_TYPE_TEXT",
		2: "MSG_TYPE_IMAGE",
		3: "MSG_TYPE_FILE",
		4: "MSG_TYPE_VOICE",
	}
	MsgType_value = map[string]int32{
		"MSG_TYPE_UNSPECIFIED": 0,
		"MSG_TYPE_TEXT":        1,
		"MSG_TYPE_IMAGE":       2,
		"MSG_TYPE_FILE":        3,
		"MSG_TYPE_VOICE":       4,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_im_v1_message_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_im_v1_message_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{0}
}

// Client-to-server request
type SendMessageRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Topic            string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	MsgType          MsgType                `protobuf:"varint,2,opt,name=msg_type,json=msgType,proto3,enum=api.im.v1.MsgType" json:"msg_type,omitempty"`
	Content          []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId      string                 `protobuf:"bytes,4,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	MentionedUserIds []int64                `protobuf:"varint,5,rep,packed,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"` // for group @mentions
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_im_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SendMessageRequest) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MSG_TYPE_UNSPECIFIED
}

func (x *SendMessageRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SendMessageRequest) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessageRequest) GetMentionedUserIds() []int64 {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

// ACK
type SendMessageReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientMsgId   string                 `protobuf:"bytes,1,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	MsgId         int64                  `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TopicSeq      uint64                 `protobuf:"varint,4,opt,name=topic_seq,json=topicSeq,proto3" json:"topic_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_im_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageReply) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *SendMessageReply) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *SendMessageReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SendMessageReply) GetTopicSeq() uint64 {
	if x != nil {
		return x.TopicSeq
	}
	return 0
}

// Push
type MessagePush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TopicSeq      uint64                 `protobuf:"varint,7,opt,name=topic_seq,json=topicSeq,proto3" json:"topic_seq,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,8,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	Recalled      bool                   `protobuf:"varint,9,opt,name=recalled,proto3" json:"recalled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePush) Reset() {
	*x = MessagePush{}
	mi := &file_im_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePush) ProtoMessage() {}

func (x *MessagePush) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePush.ProtoReflect.Descriptor instead.
func (*MessagePush) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *MessagePush) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessagePush) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MessagePush) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessagePush) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *MessagePush) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MessagePush) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessagePush) GetTopicSeq() uint64 {
	if x != nil {
		return x.TopicSeq
	}
	return 0
}

func (x *MessagePush) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessagePush) GetRecalled() bool {
	if x != nil {
		return x.Recalled
	}
	return false
}

// UpstreamMessage is sent from the Gateway to Kafka.
// MsgWorker consumes these messages to persist and dispatch them.
type UpstreamMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SenderId         int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Topic            string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	MsgType          int32                  `protobuf:"varint,3,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content          []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ClientMsgId      string                 `protobuf:"bytes,5,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	Timestamp        int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MentionedUserIds []int64                `protobuf:"varint,7,rep,packed,name=mentioned_user_ids,json=mentionedUserIds,proto3" json:"mentioned_user_ids,omitempty"` // for group @mentions
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpstreamMessage) Reset() {
	*x = UpstreamMessage{}
	mi := &file_im_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamMessage) ProtoMessage() {}

func (x *UpstreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamMessage.ProtoReflect.Descriptor instead.
func (*UpstreamMessage) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *UpstreamMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *UpstreamMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *UpstreamMessage) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *UpstreamMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpstreamMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *UpstreamMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *UpstreamMessage) GetMentionedUserIds() []int64 {
	if x != nil {
		return x.MentionedUserIds
	}
	return nil
}

// PullRequest is sent by client to pull messages.
//
// Two mutually exclusive modes:
//   - Forward (incremental): last_seq > 0, end_seq == 0. Returns messages
//     with seq > last_seq in ascending order (offline catch-up).
//   - Backward (history): end_seq > 0, or both zero. Returns the latest
//     messages with seq < end_seq (or the latest overall when end_seq == 0)
//     in ascending order, for paging history backwards. Use the oldest
//     returned topic_seq as the next end_seq.
type PullRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	LastSeq       uint64                 `protobuf:"varint,2,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"` // client last known seq, fetch messages with seq > last_seq
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	EndSeq        uint64                 `protobuf:"varint,4,opt,name=end_seq,json=endSeq,proto3" json:"end_seq,omitempty"` // exclusive upper bound; 0 = from the latest (backward history page)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_im_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *PullRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PullRequest) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *PullRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PullRequest) GetEndSeq() uint64 {
	if x != nil {
		return x.EndSeq
	}
	return 0
}

// PullMessage is a message in the pull response.
type PullMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	MsgType       int32                  `protobuf:"varint,4,opt,name=msg_type,json=msgType,proto3" json:"msg_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TopicSeq      uint64                 `protobuf:"varint,7,opt,name=topic_seq,json=topicSeq,proto3" json:"topic_seq,omitempty"`
	ClientMsgId   string                 `protobuf:"bytes,8,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	Recalled      bool                   `protobuf:"varint,9,opt,name=recalled,proto3" json:"recalled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessage) Reset() {
	*x = PullMessage{}
	mi := &file_im_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessage) ProtoMessage() {}

func (x *PullMessage) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessage.ProtoReflect.Descriptor instead.
func (*PullMessage) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *PullMessage) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PullMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PullMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *PullMessage) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *PullMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PullMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PullMessage) GetTopicSeq() uint64 {
	if x != nil {
		return x.TopicSeq
	}
	return 0
}

func (x *PullMessage) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *PullMessage) GetRecalled() bool {
	if x != nil {
		return x.Recalled
	}
	return false
}

// PullReply is sent by server in response to PullRequest.
type PullReply struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Messages []*PullMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore  bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// Forward mode: next seq to pull from (> last returned seq).
	// Backward mode: oldest returned seq, suitable as the next end_seq.
	NextSeq       uint64 `protobuf:"varint,3,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullReply) Reset() {
	*x = PullReply{}
	mi := &file_im_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullReply) ProtoMessage() {}

func (x *PullReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullReply.ProtoReflect.Descriptor instead.
func (*PullReply) Descriptor() ([]byte, []int) {
	return file_im_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *PullReply) GetMessages() []*PullMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *PullReply) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *PullReply) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

var File_im_v1_message_proto protoreflect.FileDescriptor

const file_im_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x13im/v1/message.proto\x12\tapi.im.v1\x1a\x1cgoogle/api/annotations.proto\"\xc5\x01\n" +
	"\x12SendMessageRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12-\n" +
	"\bmsg_type\x18\x02 \x01(\x0e2\x12.api.im.v1.MsgTypeR\amsgType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x04 \x01(\tR\vclientMsgId\x12,\n" +
	"\x12mentioned_user_ids\x18\x05 \x03(\x03R\x10mentionedUserIds\"\x88\x01\n" +
	"\x10SendMessageReply\x12\"\n" +
	"\rclient_msg_id\x18\x01 \x01(\tR\vclientMsgId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\x03R\x05msgId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\ttopic_seq\x18\x04 \x01(\x04R\btopicSeq\"\x87\x02\n" +
	"\vMessagePush\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x19\n" +
	"\bmsg_type\x18\x04 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\ttopic_seq\x18\a \x01(\x04R\btopicSeq\x12\"\n" +
	"\rclient_msg_id\x18\b \x01(\tR\vclientMsgId\x12\x1a\n" +
	"\brecalled\x18\t \x01(\bR\brecalled\"\xe9\x01\n" +
	"\x0fUpstreamMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x19\n" +
	"\bmsg_type\x18\x03 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\"\n" +
	"\rclient_msg_id\x18\x05 \x01(\tR\vclientMsgId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12,\n" +
	"\x12mentioned_user_ids\x18\a \x03(\x03R\x10mentionedUserIds\"m\n" +
	"\vPullRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x19\n" +
	"\blast_seq\x18\x02 \x01(\x04R\alastSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x17\n" +
	"\aend_seq\x18\x04 \x01(\x04R\x06endSeq\"\x87\x02\n" +
	"\vPullMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x19\n" +
	"\bmsg_type\x18\x04 \x01(\x05R\amsgType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\ttopic_seq\x18\a \x01(\x04R\btopicSeq\x12\"\n" +
	"\rclient_msg_id\x18\b \x01(\tR\vclientMsgId\x12\x1a\n" +
	"\brecalled\x18\t \x01(\bR\brecalled\"u\n" +
	"\tPullReply\x122\n" +
	"\bmessages\x18\x01 \x03(\v2\x16.api.im.v1.PullMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x19\n" +
	"\bnext_seq\x18\x03 \x01(\x04R\anextSeq*q\n" +
	"\aMsgType\x12\x18\n" +
	"\x14MSG_TYPE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMSG_TYPE_TEXT\x10\x01\x12\x12\n" +
	"\x0eMSG_TYPE_IMAGE\x10\x02\x12\x11\n" +
	"\rMSG_TYPE_FILE\x10\x03\x12\x12\n" +
	"\x0eMSG_TYPE_VOICE\x10\x042\xd0\x01\n" +
	"\x0eMessageService\x12f\n" +
	"\vSendMessage\x12\x1d.api.im.v1.SendMessageRequest\x1a\x1b.api.im.v1.SendMessageReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/message/send\x12V\n" +
	"\fPullMessages\x12\x16.api.im.v1.PullRequest\x1a\x14.api.im.v1.PullReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/message/pullB\x18Z\x16nonoka-im/api/im/v1;v1b\x06proto3"

var (
	file_im_v1_message_proto_rawDescOnce sync.Once
	file_im_v1_message_proto_rawDescData []byte
)

func file_im_v1_message_proto_rawDescGZIP() []byte {
	file_im_v1_message_proto_rawDescOnce.Do(func() {
		file_im_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_v1_message_proto_rawDesc), len(file_im_v1_message_proto_rawDesc)))
	})
	return file_im_v1_message_proto_rawDescData
}

var file_im_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_im_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_im_v1_message_proto_goTypes = []any{
	(MsgType)(0),               // 0: api.im.v1.MsgType
	(*SendMessageRequest)(nil), // 1: api.im.v1.SendMessageRequest
	(*SendMessageReply)(nil),   // 2: api.im.v1.SendMessageReply
	(*MessagePush)(nil),        // 3: api.im.v1.MessagePush
	(*UpstreamMessage)(nil),    // 4: api.im.v1.UpstreamMessage
	(*PullRequest)(nil),        // 5: api.im.v1.PullRequest
	(*PullMessage)(nil),        // 6: api.im.v1.PullMessage
	(*PullReply)(nil),          // 7: api.im.v1.PullReply
}
var file_im_v1_message_proto_depIdxs = []int32{
	0, // 0: api.im.v1.SendMessageRequest.msg_type:type_name -> api.im.v1.MsgType
	6, // 1: api.im.v1.PullReply.messages:type_name -> api.im.v1.PullMessage
	1, // 2: api.im.v1.MessageService.SendMessage:input_type -> api.im.v1.SendMessageRequest
	5, // 3: api.im.v1.MessageService.PullMessages:input_type -> api.im.v1.PullRequest
	2, // 4: api.im.v1.MessageService.SendMessage:output_type -> api.im.v1.SendMessageReply
	7, // 5: api.im.v1.MessageService.PullMessages:output_type -> api.im.v1.PullReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_im_v1_message_proto_init() }
func file_im_v1_message_proto_init() {
	if File_im_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_v1_message_proto_rawDesc), len(file_im_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_v1_message_proto_goTypes,
		DependencyIndexes: file_im_v1_message_proto_depIdxs,
		EnumInfos:         file_im_v1_message_proto_enumTypes,
		MessageInfos:      file_im_v1_message_proto_msgTypes,
	}.Build()
	File_im_v1_message_proto = out.File
	file_im_v1_message_proto_goTypes = nil
	file_im_v1_message_proto_depIdxs = nil
}
