// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: im/v1/packet.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command int32

const (
	Command_CMD_UNKNOWN   Command = 0
	Command_CMD_HEARTBEAT Command = 1
	Command_CMD_AUTH      Command = 2
	Command_CMD_PUBLISH   Command = 3 // client -> server: send message
	Command_CMD_ACK       Command = 4 // bi-directional: message ack
	Command_CMD_PULL      Command = 5 // client -> server: pull offline messages
	Command_CMD_NOTIFY    Command = 6 // server -> client: push notification
)

// Enum value maps for Command.
var (
	Command_name = map[int32]string{
		0: "CMD_UNKNOWN",
		1: "CMD_HEARTBEAT",
		2: "CMD_AUTH",
		3: "CMD_PUBLISH",
		4: "CMD_ACK",
		5: "CMD_PULL",
		6: "CMD_NOTIFY",
	}
	Command_value = map[string]int32{
		"CMD_UNKNOWN":   0,
		"CMD_HEARTBEAT": 1,
		"CMD_AUTH":      2,
		"CMD_PUBLISH":   3,
		"CMD_ACK":       4,
		"CMD_PULL":      5,
		"CMD_NOTIFY":    6,
	}
)

func (x Command) Enum() *Command {
	p := new(Command)
	*p = x
	return p
}

func (x Command) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command) Descriptor() protoreflect.EnumDescriptor {
	return file_im_v1_packet_proto_enumTypes[0].Descriptor()
}

func (Command) Type() protoreflect.EnumType {
	return &file_im_v1_packet_proto_enumTypes[0]
}

func (x Command) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command.Descriptor instead.
func (Command) EnumDescriptor() ([]byte, []int) {
	return file_im_v1_packet_proto_rawDescGZIP(), []int{0}
}

type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           Command                `protobuf:"varint,1,opt,name=cmd,proto3,enum=api.im.v1.Command" json:"cmd,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_im_v1_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_im_v1_packet_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetCmd() Command {
	if x != nil {
		return x.Cmd
	}
	return Command_CMD_UNKNOWN
}

func (x *Packet) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Packet) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_im_v1_packet_proto protoreflect.FileDescriptor

const file_im_v1_packet_proto_rawDesc = "" +
	"\n" +
	"\x12im/v1/packet.proto\x12\tapi.im.v1\"Z\n" +
	"\x06Packet\x12$\n" +
	"\x03cmd\x18\x01 \x01(\x0e2\x12.api.im.v1.CommandR\x03cmd\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload*w\n" +
	"\aCommand\x12\x0f\n" +
	"\vCMD_UNKNOWN\x10\x00\x12\x11\n" +
	"\rCMD_HEARTBEAT\x10\x01\x12\f\n" +
	"\bCMD_AUTH\x10\x02\x12\x0f\n" +
	"\vCMD_PUBLISH\x10\x03\x12\v\n" +
	"\aCMD_ACK\x10\x04\x12\f\n" +
	"\bCMD_PULL\x10\x05\x12\x0e\n" +
	"\n" +
	"CMD_NOTIFY\x10\x06B\x18Z\x16nonoka-im/api/im/v1;v1b\x06proto3"

var (
	file_im_v1_packet_proto_rawDescOnce sync.Once
	file_im_v1_packet_proto_rawDescData []byte
)

func file_im_v1_packet_proto_rawDescGZIP() []byte {
	file_im_v1_packet_proto_rawDescOnce.Do(func() {
		file_im_v1_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_v1_packet_proto_rawDesc), len(file_im_v1_packet_proto_rawDesc)))
	})
	return file_im_v1_packet_proto_rawDescData
}

var file_im_v1_packet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_im_v1_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_im_v1_packet_proto_goTypes = []any{
	(Command)(0),   // 0: api.im.v1.Command
	(*Packet)(nil), // 1: api.im.v1.Packet
}
var file_im_v1_packet_proto_depIdxs = []int32{
	0, // 0: api.im.v1.Packet.cmd:type_name -> api.im.v1.Command
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_im_v1_packet_proto_init() }
func file_im_v1_packet_proto_init() {
	if File_im_v1_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_v1_packet_proto_rawDesc), len(file_im_v1_packet_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_im_v1_packet_proto_goTypes,
		DependencyIndexes: file_im_v1_packet_proto_depIdxs,
		EnumInfos:         file_im_v1_packet_proto_enumTypes,
		MessageInfos:      file_im_v1_packet_proto_msgTypes,
	}.Build()
	File_im_v1_packet_proto = out.File
	file_im_v1_packet_proto_goTypes = nil
	file_im_v1_packet_proto_depIdxs = nil
}
