// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: im/v1/push.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushToUserRequest is sent by MsgWorker to Gateway.
type PushToUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Message       *MessagePush           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushToUserRequest) Reset() {
	*x = PushToUserRequest{}
	mi := &file_im_v1_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserRequest) ProtoMessage() {}

func (x *PushToUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserRequest.ProtoReflect.Descriptor instead.
func (*PushToUserRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushToUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PushToUserRequest) GetMessage() *MessagePush {
	if x != nil {
		return x.Message
	}
	return nil
}

type PushToUserReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeliveredCount int32                  `protobuf:"varint,2,opt,name=delivered_count,json=deliveredCount,proto3" json:"delivered_count,omitempty"` // number of devices the message was sent to
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushToUserReply) Reset() {
	*x = PushToUserReply{}
	mi := &file_im_v1_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushToUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushToUserReply) ProtoMessage() {}

func (x *PushToUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushToUserReply.ProtoReflect.Descriptor instead.
func (*PushToUserReply) Descriptor() ([]byte, []int) {
	return file_im_v1_push_proto_rawDescGZIP(), []int{1}
}

func (x *PushToUserReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushToUserReply) GetDeliveredCount() int32 {
	if x != nil {
		return x.DeliveredCount
	}
	return 0
}

// BatchPushToUsersRequest pushes a message to multiple users.
type BatchPushToUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Message       *MessagePush           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPushToUsersRequest) Reset() {
	*x = BatchPushToUsersRequest{}
	mi := &file_im_v1_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPushToUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPushToUsersRequest) ProtoMessage() {}

func (x *BatchPushToUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPushToUsersRequest.ProtoReflect.Descriptor instead.
func (*BatchPushToUsersRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_push_proto_rawDescGZIP(), []int{2}
}

func (x *BatchPushToUsersRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *BatchPushToUsersRequest) GetMessage() *MessagePush {
	if x != nil {
		return x.Message
	}
	return nil
}

type BatchPushToUsersReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalDelivered int32                  `protobuf:"varint,1,opt,name=total_delivered,json=totalDelivered,proto3" json:"total_delivered,omitempty"`
	FailedUserIds  []int64                `protobuf:"varint,2,rep,packed,name=failed_user_ids,json=failedUserIds,proto3" json:"failed_user_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchPushToUsersReply) Reset() {
	*x = BatchPushToUsersReply{}
	mi := &file_im_v1_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPushToUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPushToUsersReply) ProtoMessage() {}

func (x *BatchPushToUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPushToUsersReply.ProtoReflect.Descriptor instead.
func (*BatchPushToUsersReply) Descriptor() ([]byte, []int) {
	return file_im_v1_push_proto_rawDescGZIP(), []int{3}
}

func (x *BatchPushToUsersReply) GetTotalDelivered() int32 {
	if x != nil {
		return x.TotalDelivered
	}
	return 0
}

func (x *BatchPushToUsersReply) GetFailedUserIds() []int64 {
	if x != nil {
		return x.FailedUserIds
	}
	return nil
}

var File_im_v1_push_proto protoreflect.FileDescriptor

const file_im_v1_push_proto_rawDesc = "" +
	"\n" +
	"\x10im/v1/push.proto\x12\tapi.im.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x13im/v1/message.proto\"^\n" +
	"\x11PushToUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x120\n" +
	"\amessage\x18\x02 \x01(\v2\x16.api.im.v1.MessagePushR\amessage\"T\n" +
	"\x0fPushToUserReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fdelivered_count\x18\x02 \x01(\x05R\x0edeliveredCount\"f\n" +
	"\x17BatchPushToUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\x120\n" +
	"\amessage\x18\x02 \x01(\v2\x16.api.im.v1.MessagePushR\amessage\"h\n" +
	"\x15BatchPushToUsersReply\x12'\n" +
	"\x0ftotal_delivered\x18\x01 \x01(\x05R\x0etotalDelivered\x12&\n" +
	"\x0ffailed_user_ids\x18\x02 \x03(\x03R\rfailedUserIds2\xaf\x01\n" +
	"\vPushService\x12F\n" +
	"\n" +
	"PushToUser\x12\x1c.api.im.v1.PushToUserRequest\x1a\x1a.api.im.v1.PushToUserReply\x12X\n" +
	"\x10BatchPushToUsers\x12\".api.im.v1.BatchPushToUsersRequest\x1a .api.im.v1.BatchPushToUsersReplyB\x18Z\x16nonoka-im/api/im/v1;v1b\x06proto3"

var (
	file_im_v1_push_proto_rawDescOnce sync.Once
	file_im_v1_push_proto_rawDescData []byte
)

func file_im_v1_push_proto_rawDescGZIP() []byte {
	file_im_v1_push_proto_rawDescOnce.Do(func() {
		file_im_v1_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_v1_push_proto_rawDesc), len(file_im_v1_push_proto_rawDesc)))
	})
	return file_im_v1_push_proto_rawDescData
}

var file_im_v1_push_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_im_v1_push_proto_goTypes = []any{
	(*PushToUserRequest)(nil),       // 0: api.im.v1.PushToUserRequest
	(*PushToUserReply)(nil),         // 1: api.im.v1.PushToUserReply
	(*BatchPushToUsersRequest)(nil), // 2: api.im.v1.BatchPushToUsersRequest
	(*BatchPushToUsersReply)(nil),   // 3: api.im.v1.BatchPushToUsersReply
	(*MessagePush)(nil),             // 4: api.im.v1.MessagePush
}
var file_im_v1_push_proto_depIdxs = []int32{
	4, // 0: api.im.v1.PushToUserRequest.message:type_name -> api.im.v1.MessagePush
	4, // 1: api.im.v1.BatchPushToUsersRequest.message:type_name -> api.im.v1.MessagePush
	0, // 2: api.im.v1.PushService.PushToUser:input_type -> api.im.v1.PushToUserRequest
	2, // 3: api.im.v1.PushService.BatchPushToUsers:input_type -> api.im.v1.BatchPushToUsersRequest
	1, // 4: api.im.v1.PushService.PushToUser:output_type -> api.im.v1.PushToUserReply
	3, // 5: api.im.v1.PushService.BatchPushToUsers:output_type -> api.im.v1.BatchPushToUsersReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_im_v1_push_proto_init() }
func file_im_v1_push_proto_init() {
	if File_im_v1_push_proto != nil {
		return
	}
	file_im_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_v1_push_proto_rawDesc), len(file_im_v1_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_v1_push_proto_goTypes,
		DependencyIndexes: file_im_v1_push_proto_depIdxs,
		MessageInfos:      file_im_v1_push_proto_msgTypes,
	}.Build()
	File_im_v1_push_proto = out.File
	file_im_v1_push_proto_goTypes = nil
	file_im_v1_push_proto_depIdxs = nil
}
