// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: im/v1/push.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PushService_PushToUser_FullMethodName               = "/api.im.v1.PushService/PushToUser"
	PushService_BatchPushToUsers_FullMethodName         = "/api.im.v1.PushService/BatchPushToUsers"
	PushService_PushReceiptToUser_FullMethodName        = "/api.im.v1.PushService/PushReceiptToUser"
	PushService_BatchPushReceiptToUsers_FullMethodName  = "/api.im.v1.PushService/BatchPushReceiptToUsers"
	PushService_BatchPushReceiptsToUsers_FullMethodName = "/api.im.v1.PushService/BatchPushReceiptsToUsers"
)

// PushServiceClient is the client API for PushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PushService is exposed by the Gateway for MsgWorker to push messages to online users.
type PushServiceClient interface {
	// PushToUser delivers a message to all online devices of a user.
	PushToUser(ctx context.Context, in *PushToUserRequest, opts ...grpc.CallOption) (*PushToUserReply, error)
	// BatchPushToUsers delivers messages to multiple users in one call.
	BatchPushToUsers(ctx context.Context, in *BatchPushToUsersRequest, opts ...grpc.CallOption) (*BatchPushToUsersReply, error)
	// PushReceiptToUser delivers a send receipt to all online devices of a user.
	PushReceiptToUser(ctx context.Context, in *PushReceiptToUserRequest, opts ...grpc.CallOption) (*PushReceiptToUserReply, error)
	// BatchPushReceiptToUsers delivers the SAME send receipt to multiple users in one call.
	BatchPushReceiptToUsers(ctx context.Context, in *BatchPushReceiptToUsersRequest, opts ...grpc.CallOption) (*BatchPushReceiptToUsersReply, error)
	// BatchPushReceiptsToUsers delivers MULTIPLE distinct send receipts to multiple users in one call.
	// This is used by MsgWorker to aggregate short-term receipts for the same user.
	BatchPushReceiptsToUsers(ctx context.Context, in *BatchPushReceiptsToUsersRequest, opts ...grpc.CallOption) (*BatchPushReceiptsToUsersReply, error)
}

type pushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushServiceClient(cc grpc.ClientConnInterface) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) PushToUser(ctx context.Context, in *PushToUserRequest, opts ...grpc.CallOption) (*PushToUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushToUserReply)
	err := c.cc.Invoke(ctx, PushService_PushToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) BatchPushToUsers(ctx context.Context, in *BatchPushToUsersRequest, opts ...grpc.CallOption) (*BatchPushToUsersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPushToUsersReply)
	err := c.cc.Invoke(ctx, PushService_BatchPushToUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) PushReceiptToUser(ctx context.Context, in *PushReceiptToUserRequest, opts ...grpc.CallOption) (*PushReceiptToUserReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushReceiptToUserReply)
	err := c.cc.Invoke(ctx, PushService_PushReceiptToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) BatchPushReceiptToUsers(ctx context.Context, in *BatchPushReceiptToUsersRequest, opts ...grpc.CallOption) (*BatchPushReceiptToUsersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPushReceiptToUsersReply)
	err := c.cc.Invoke(ctx, PushService_BatchPushReceiptToUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) BatchPushReceiptsToUsers(ctx context.Context, in *BatchPushReceiptsToUsersRequest, opts ...grpc.CallOption) (*BatchPushReceiptsToUsersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchPushReceiptsToUsersReply)
	err := c.cc.Invoke(ctx, PushService_BatchPushReceiptsToUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServiceServer is the server API for PushService service.
// All implementations must embed UnimplementedPushServiceServer
// for forward compatibility.
//
// PushService is exposed by the Gateway for MsgWorker to push messages to online users.
type PushServiceServer interface {
	// PushToUser delivers a message to all online devices of a user.
	PushToUser(context.Context, *PushToUserRequest) (*PushToUserReply, error)
	// BatchPushToUsers delivers messages to multiple users in one call.
	BatchPushToUsers(context.Context, *BatchPushToUsersRequest) (*BatchPushToUsersReply, error)
	// PushReceiptToUser delivers a send receipt to all online devices of a user.
	PushReceiptToUser(context.Context, *PushReceiptToUserRequest) (*PushReceiptToUserReply, error)
	// BatchPushReceiptToUsers delivers the SAME send receipt to multiple users in one call.
	BatchPushReceiptToUsers(context.Context, *BatchPushReceiptToUsersRequest) (*BatchPushReceiptToUsersReply, error)
	// BatchPushReceiptsToUsers delivers MULTIPLE distinct send receipts to multiple users in one call.
	// This is used by MsgWorker to aggregate short-term receipts for the same user.
	BatchPushReceiptsToUsers(context.Context, *BatchPushReceiptsToUsersRequest) (*BatchPushReceiptsToUsersReply, error)
	mustEmbedUnimplementedPushServiceServer()
}

// UnimplementedPushServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushServiceServer struct{}

func (UnimplementedPushServiceServer) PushToUser(context.Context, *PushToUserRequest) (*PushToUserReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PushToUser not implemented")
}
func (UnimplementedPushServiceServer) BatchPushToUsers(context.Context, *BatchPushToUsersRequest) (*BatchPushToUsersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPushToUsers not implemented")
}
func (UnimplementedPushServiceServer) PushReceiptToUser(context.Context, *PushReceiptToUserRequest) (*PushReceiptToUserReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PushReceiptToUser not implemented")
}
func (UnimplementedPushServiceServer) BatchPushReceiptToUsers(context.Context, *BatchPushReceiptToUsersRequest) (*BatchPushReceiptToUsersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPushReceiptToUsers not implemented")
}
func (UnimplementedPushServiceServer) BatchPushReceiptsToUsers(context.Context, *BatchPushReceiptsToUsersRequest) (*BatchPushReceiptsToUsersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchPushReceiptsToUsers not implemented")
}
func (UnimplementedPushServiceServer) mustEmbedUnimplementedPushServiceServer() {}
func (UnimplementedPushServiceServer) testEmbeddedByValue()                     {}

// UnsafePushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServiceServer will
// result in compilation errors.
type UnsafePushServiceServer interface {
	mustEmbedUnimplementedPushServiceServer()
}

func RegisterPushServiceServer(s grpc.ServiceRegistrar, srv PushServiceServer) {
	// If the following call panics, it indicates UnimplementedPushServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushService_ServiceDesc, srv)
}

func _PushService_PushToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).PushToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_PushToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).PushToUser(ctx, req.(*PushToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_BatchPushToUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPushToUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).BatchPushToUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_BatchPushToUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).BatchPushToUsers(ctx, req.(*BatchPushToUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_PushReceiptToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushReceiptToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).PushReceiptToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_PushReceiptToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).PushReceiptToUser(ctx, req.(*PushReceiptToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_BatchPushReceiptToUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPushReceiptToUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).BatchPushReceiptToUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_BatchPushReceiptToUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).BatchPushReceiptToUsers(ctx, req.(*BatchPushReceiptToUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_BatchPushReceiptsToUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchPushReceiptsToUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).BatchPushReceiptsToUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushService_BatchPushReceiptsToUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).BatchPushReceiptsToUsers(ctx, req.(*BatchPushReceiptsToUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PushService_ServiceDesc is the grpc.ServiceDesc for PushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.im.v1.PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushToUser",
			Handler:    _PushService_PushToUser_Handler,
		},
		{
			MethodName: "BatchPushToUsers",
			Handler:    _PushService_BatchPushToUsers_Handler,
		},
		{
			MethodName: "PushReceiptToUser",
			Handler:    _PushService_PushReceiptToUser_Handler,
		},
		{
			MethodName: "BatchPushReceiptToUsers",
			Handler:    _PushService_BatchPushReceiptToUsers_Handler,
		},
		{
			MethodName: "BatchPushReceiptsToUsers",
			Handler:    _PushService_BatchPushReceiptsToUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im/v1/push.proto",
}
