// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: im/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // supports prefix matching
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_im_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_im_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *SearchUsersRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SearchUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchUsersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersReply) Reset() {
	*x = SearchUsersReply{}
	mi := &file_im_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersReply) ProtoMessage() {}

func (x *SearchUsersReply) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersReply.ProtoReflect.Descriptor instead.
func (*SearchUsersReply) Descriptor() ([]byte, []int) {
	return file_im_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *SearchUsersReply) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_im_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_im_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_im_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_im_v1_user_proto protoreflect.FileDescriptor

const file_im_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x10im/v1/user.proto\x12\tapi.im.v1\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\x12SearchUsersRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"9\n" +
	"\x10SearchUsersReply\x12%\n" +
	"\x05users\x18\x01 \x03(\v2\x0f.api.im.v1.UserR\x05users\";\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername2r\n" +
	"\vUserService\x12c\n" +
	"\vSearchUsers\x12\x1d.api.im.v1.SearchUsersRequest\x1a\x1b.api.im.v1.SearchUsersReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/users/searchB\x18Z\x16nonoka-im/api/im/v1;v1b\x06proto3"

var (
	file_im_v1_user_proto_rawDescOnce sync.Once
	file_im_v1_user_proto_rawDescData []byte
)

func file_im_v1_user_proto_rawDescGZIP() []byte {
	file_im_v1_user_proto_rawDescOnce.Do(func() {
		file_im_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_im_v1_user_proto_rawDesc), len(file_im_v1_user_proto_rawDesc)))
	})
	return file_im_v1_user_proto_rawDescData
}

var file_im_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_im_v1_user_proto_goTypes = []any{
	(*SearchUsersRequest)(nil), // 0: api.im.v1.SearchUsersRequest
	(*SearchUsersReply)(nil),   // 1: api.im.v1.SearchUsersReply
	(*User)(nil),               // 2: api.im.v1.User
}
var file_im_v1_user_proto_depIdxs = []int32{
	2, // 0: api.im.v1.SearchUsersReply.users:type_name -> api.im.v1.User
	0, // 1: api.im.v1.UserService.SearchUsers:input_type -> api.im.v1.SearchUsersRequest
	1, // 2: api.im.v1.UserService.SearchUsers:output_type -> api.im.v1.SearchUsersReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_im_v1_user_proto_init() }
func file_im_v1_user_proto_init() {
	if File_im_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_im_v1_user_proto_rawDesc), len(file_im_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_im_v1_user_proto_goTypes,
		DependencyIndexes: file_im_v1_user_proto_depIdxs,
		MessageInfos:      file_im_v1_user_proto_msgTypes,
	}.Build()
	File_im_v1_user_proto = out.File
	file_im_v1_user_proto_goTypes = nil
	file_im_v1_user_proto_depIdxs = nil
}
