// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Data          *Data                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Dispatch      *Dispatch              `protobuf:"bytes,4,opt,name=dispatch,proto3" json:"dispatch,omitempty"`
	Gateway       *GatewayConfig         `protobuf:"bytes,5,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Msgworker     *MsgworkerConfig       `protobuf:"bytes,6,opt,name=msgworker,proto3" json:"msgworker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetDispatch() *Dispatch {
	if x != nil {
		return x.Dispatch
	}
	return nil
}

func (x *Bootstrap) GetGateway() *GatewayConfig {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *Bootstrap) GetMsgworker() *MsgworkerConfig {
	if x != nil {
		return x.Msgworker
	}
	return nil
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Http          *Server_HTTP           `protobuf:"bytes,1,opt,name=http,proto3" json:"http,omitempty"`
	Grpc          *Server_GRPC           `protobuf:"bytes,2,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Data_Database         `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Data_Redis            `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Mongodb       *Data_MongoDB          `protobuf:"bytes,3,opt,name=mongodb,proto3" json:"mongodb,omitempty"`
	Kafka         *Data_Kafka            `protobuf:"bytes,4,opt,name=kafka,proto3" json:"kafka,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetDatabase() *Data_Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Data_Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetMongodb() *Data_MongoDB {
	if x != nil {
		return x.Mongodb
	}
	return nil
}

func (x *Data) GetKafka() *Data_Kafka {
	if x != nil {
		return x.Kafka
	}
	return nil
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtSecret     string                 `protobuf:"bytes,1,opt,name=jwt_secret,json=jwtSecret,proto3" json:"jwt_secret,omitempty"`
	TokenTtl      *durationpb.Duration   `protobuf:"bytes,2,opt,name=token_ttl,json=tokenTtl,proto3" json:"token_ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Auth) GetJwtSecret() string {
	if x != nil {
		return x.JwtSecret
	}
	return ""
}

func (x *Auth) GetTokenTtl() *durationpb.Duration {
	if x != nil {
		return x.TokenTtl
	}
	return nil
}

type GatewayNode struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GatewayUrl      string                 `protobuf:"bytes,2,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"`
	GatewayGrpcAddr string                 `protobuf:"bytes,3,opt,name=gateway_grpc_addr,json=gatewayGrpcAddr,proto3" json:"gateway_grpc_addr,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GatewayNode) Reset() {
	*x = GatewayNode{}
	mi := &file_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayNode) ProtoMessage() {}

func (x *GatewayNode) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayNode.ProtoReflect.Descriptor instead.
func (*GatewayNode) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayNode) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GatewayNode) GetGatewayUrl() string {
	if x != nil {
		return x.GatewayUrl
	}
	return ""
}

func (x *GatewayNode) GetGatewayGrpcAddr() string {
	if x != nil {
		return x.GatewayGrpcAddr
	}
	return ""
}

type GatewayConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WebSocket heartbeat interval (e.g., 30s). This controls how often
	// the server expects heartbeats from connected clients.
	HeartbeatInterval *durationpb.Duration `protobuf:"bytes,1,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// WebSocket heartbeat timeout (e.g., 90s). If no heartbeat is received
	// within this duration, the server will close the connection.
	HeartbeatTimeout *durationpb.Duration `protobuf:"bytes,2,opt,name=heartbeat_timeout,json=heartbeatTimeout,proto3" json:"heartbeat_timeout,omitempty"`
	// WebSocket read timeout (e.g., 60s). Sets the read deadline on the
	// underlying WebSocket connection.
	ReadTimeout *durationpb.Duration `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	// WebSocket write timeout (e.g., 10s). Sets the write deadline on the
	// underlying WebSocket connection. A slow client will be closed after this.
	WriteTimeout *durationpb.Duration `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	// Allowed WebSocket origins. If empty, all origins are allowed (development
	// default). In production, set this to the exact origins that may connect.
	AllowedOrigins []string `protobuf:"bytes,5,rep,name=allowed_origins,json=allowedOrigins,proto3" json:"allowed_origins,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewayConfig) Reset() {
	*x = GatewayConfig{}
	mi := &file_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayConfig) ProtoMessage() {}

func (x *GatewayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayConfig.ProtoReflect.Descriptor instead.
func (*GatewayConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *GatewayConfig) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

func (x *GatewayConfig) GetHeartbeatTimeout() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatTimeout
	}
	return nil
}

func (x *GatewayConfig) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *GatewayConfig) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *GatewayConfig) GetAllowedOrigins() []string {
	if x != nil {
		return x.AllowedOrigins
	}
	return nil
}

type Dispatch struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Gateways          []*GatewayNode         `protobuf:"bytes,1,rep,name=gateways,proto3" json:"gateways,omitempty"`
	Strategy          string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"` // "consistent_hash" | "least_connections"
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	NodeTtl           *durationpb.Duration   `protobuf:"bytes,4,opt,name=node_ttl,json=nodeTtl,proto3" json:"node_ttl,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Dispatch) Reset() {
	*x = Dispatch{}
	mi := &file_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dispatch) ProtoMessage() {}

func (x *Dispatch) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dispatch.ProtoReflect.Descriptor instead.
func (*Dispatch) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Dispatch) GetGateways() []*GatewayNode {
	if x != nil {
		return x.Gateways
	}
	return nil
}

func (x *Dispatch) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *Dispatch) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

func (x *Dispatch) GetNodeTtl() *durationpb.Duration {
	if x != nil {
		return x.NodeTtl
	}
	return nil
}

type Gateway struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	GatewayUrl    string                 `protobuf:"bytes,2,opt,name=gateway_url,json=gatewayUrl,proto3" json:"gateway_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gateway) Reset() {
	*x = Gateway{}
	mi := &file_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gateway) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gateway) ProtoMessage() {}

func (x *Gateway) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gateway.ProtoReflect.Descriptor instead.
func (*Gateway) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Gateway) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Gateway) GetGatewayUrl() string {
	if x != nil {
		return x.GatewayUrl
	}
	return ""
}

type MsgworkerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Local session route cache TTL. 0 means use default (5s).
	SessionCacheTtl *durationpb.Duration `protobuf:"bytes,1,opt,name=session_cache_ttl,json=sessionCacheTtl,proto3" json:"session_cache_ttl,omitempty"`
	// Max number of pending receipts per user before flush.
	ReceiptBatchSize int32 `protobuf:"varint,2,opt,name=receipt_batch_size,json=receiptBatchSize,proto3" json:"receipt_batch_size,omitempty"`
	// Max time to wait before flushing receipt batch.
	ReceiptBatchTimeout *durationpb.Duration `protobuf:"bytes,3,opt,name=receipt_batch_timeout,json=receiptBatchTimeout,proto3" json:"receipt_batch_timeout,omitempty"`
	// Max number of group messages to batch before MongoDB insert.
	GroupBatchSize int32 `protobuf:"varint,4,opt,name=group_batch_size,json=groupBatchSize,proto3" json:"group_batch_size,omitempty"`
	// Max time to wait before flushing group message batch.
	GroupBatchTimeout *durationpb.Duration `protobuf:"bytes,5,opt,name=group_batch_timeout,json=groupBatchTimeout,proto3" json:"group_batch_timeout,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MsgworkerConfig) Reset() {
	*x = MsgworkerConfig{}
	mi := &file_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgworkerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgworkerConfig) ProtoMessage() {}

func (x *MsgworkerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgworkerConfig.ProtoReflect.Descriptor instead.
func (*MsgworkerConfig) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *MsgworkerConfig) GetSessionCacheTtl() *durationpb.Duration {
	if x != nil {
		return x.SessionCacheTtl
	}
	return nil
}

func (x *MsgworkerConfig) GetReceiptBatchSize() int32 {
	if x != nil {
		return x.ReceiptBatchSize
	}
	return 0
}

func (x *MsgworkerConfig) GetReceiptBatchTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReceiptBatchTimeout
	}
	return nil
}

func (x *MsgworkerConfig) GetGroupBatchSize() int32 {
	if x != nil {
		return x.GroupBatchSize
	}
	return 0
}

func (x *MsgworkerConfig) GetGroupBatchTimeout() *durationpb.Duration {
	if x != nil {
		return x.GroupBatchTimeout
	}
	return nil
}

type Server_HTTP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Server_HTTP) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Data_Database struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Driver          string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Source          string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	MaxOpenConns    int32                  `protobuf:"varint,3,opt,name=max_open_conns,json=maxOpenConns,proto3" json:"max_open_conns,omitempty"`
	MaxIdleConns    int32                  `protobuf:"varint,4,opt,name=max_idle_conns,json=maxIdleConns,proto3" json:"max_idle_conns,omitempty"`
	ConnMaxLifetime *durationpb.Duration   `protobuf:"bytes,5,opt,name=conn_max_lifetime,json=connMaxLifetime,proto3" json:"conn_max_lifetime,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Data_Database) Reset() {
	*x = Data_Database{}
	mi := &file_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Database) ProtoMessage() {}

func (x *Data_Database) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Database.ProtoReflect.Descriptor instead.
func (*Data_Database) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Data_Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Data_Database) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Data_Database) GetMaxOpenConns() int32 {
	if x != nil {
		return x.MaxOpenConns
	}
	return 0
}

func (x *Data_Database) GetMaxIdleConns() int32 {
	if x != nil {
		return x.MaxIdleConns
	}
	return 0
}

func (x *Data_Database) GetConnMaxLifetime() *durationpb.Duration {
	if x != nil {
		return x.ConnMaxLifetime
	}
	return nil
}

type Data_Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	ReadTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  *durationpb.Duration   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_Redis) Reset() {
	*x = Data_Redis{}
	mi := &file_conf_conf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Redis) ProtoMessage() {}

func (x *Data_Redis) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Redis.ProtoReflect.Descriptor instead.
func (*Data_Redis) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 1}
}

func (x *Data_Redis) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Data_Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data_Redis) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Redis) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

type Data_MongoDB struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Uri      string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Database string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	// write_concern controls MongoDB durability/latency trade-off.
	// "w1" = w=1, j=false (fast, default for IM messages).
	// "majority" = w=majority, j=true (durable, slower).
	// "majority_jfalse" = w=majority, j=false (balanced).
	WriteConcern  string `protobuf:"bytes,3,opt,name=write_concern,json=writeConcern,proto3" json:"write_concern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data_MongoDB) Reset() {
	*x = Data_MongoDB{}
	mi := &file_conf_conf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_MongoDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_MongoDB) ProtoMessage() {}

func (x *Data_MongoDB) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_MongoDB.ProtoReflect.Descriptor instead.
func (*Data_MongoDB) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 2}
}

func (x *Data_MongoDB) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *Data_MongoDB) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Data_MongoDB) GetWriteConcern() string {
	if x != nil {
		return x.WriteConcern
	}
	return ""
}

type Data_Kafka struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Brokers       []string               `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	ConsumerGroup string                 `protobuf:"bytes,3,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	// Producer settings
	BatchSize    int32                `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	BatchTimeout *durationpb.Duration `protobuf:"bytes,5,opt,name=batch_timeout,json=batchTimeout,proto3" json:"batch_timeout,omitempty"`
	Compression  string               `protobuf:"bytes,6,opt,name=compression,proto3" json:"compression,omitempty"`                       // "none" | "gzip" | "snappy" | "lz4" | "zstd"
	RequiredAcks string               `protobuf:"bytes,7,opt,name=required_acks,json=requiredAcks,proto3" json:"required_acks,omitempty"` // "none" | "one" | "all"
	Async        bool                 `protobuf:"varint,8,opt,name=async,proto3" json:"async,omitempty"`                                  // true = async producer (higher throughput, lower durability)
	MaxAttempts  int32                `protobuf:"varint,9,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	WriteTimeout *durationpb.Duration `protobuf:"bytes,10,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	ReadTimeout  *durationpb.Duration `protobuf:"bytes,11,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	// Consumer settings
	WorkerCount         int32                `protobuf:"varint,12,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"`
	MinBytes            int32                `protobuf:"varint,13,opt,name=min_bytes,json=minBytes,proto3" json:"min_bytes,omitempty"`
	MaxBytes            int32                `protobuf:"varint,14,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	MaxWait             *durationpb.Duration `protobuf:"bytes,15,opt,name=max_wait,json=maxWait,proto3" json:"max_wait,omitempty"`
	CommitInterval      *durationpb.Duration `protobuf:"bytes,16,opt,name=commit_interval,json=commitInterval,proto3" json:"commit_interval,omitempty"`                  // 0 = manual commit (stronger consistency)
	MaxRetries          int32                `protobuf:"varint,17,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`                             // local retry count before DLQ; 0 = DLQ immediately
	StartOffset         int64                `protobuf:"varint,18,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`                          // -1 = first offset, -2 = last offset (kafka-go constants)
	CommitBatchSize     int32                `protobuf:"varint,19,opt,name=commit_batch_size,json=commitBatchSize,proto3" json:"commit_batch_size,omitempty"`            // number of messages to batch before committing offsets
	CommitFlushInterval *durationpb.Duration `protobuf:"bytes,20,opt,name=commit_flush_interval,json=commitFlushInterval,proto3" json:"commit_flush_interval,omitempty"` // max interval between offset commits
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Data_Kafka) Reset() {
	*x = Data_Kafka{}
	mi := &file_conf_conf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data_Kafka) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data_Kafka) ProtoMessage() {}

func (x *Data_Kafka) ProtoReflect() protoreflect.Message {
	mi := &file_conf_conf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data_Kafka.ProtoReflect.Descriptor instead.
func (*Data_Kafka) Descriptor() ([]byte, []int) {
	return file_conf_conf_proto_rawDescGZIP(), []int{2, 3}
}

func (x *Data_Kafka) GetBrokers() []string {
	if x != nil {
		return x.Brokers
	}
	return nil
}

func (x *Data_Kafka) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Data_Kafka) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *Data_Kafka) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *Data_Kafka) GetBatchTimeout() *durationpb.Duration {
	if x != nil {
		return x.BatchTimeout
	}
	return nil
}

func (x *Data_Kafka) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *Data_Kafka) GetRequiredAcks() string {
	if x != nil {
		return x.RequiredAcks
	}
	return ""
}

func (x *Data_Kafka) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *Data_Kafka) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Data_Kafka) GetWriteTimeout() *durationpb.Duration {
	if x != nil {
		return x.WriteTimeout
	}
	return nil
}

func (x *Data_Kafka) GetReadTimeout() *durationpb.Duration {
	if x != nil {
		return x.ReadTimeout
	}
	return nil
}

func (x *Data_Kafka) GetWorkerCount() int32 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

func (x *Data_Kafka) GetMinBytes() int32 {
	if x != nil {
		return x.MinBytes
	}
	return 0
}

func (x *Data_Kafka) GetMaxBytes() int32 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *Data_Kafka) GetMaxWait() *durationpb.Duration {
	if x != nil {
		return x.MaxWait
	}
	return nil
}

func (x *Data_Kafka) GetCommitInterval() *durationpb.Duration {
	if x != nil {
		return x.CommitInterval
	}
	return nil
}

func (x *Data_Kafka) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *Data_Kafka) GetStartOffset() int64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *Data_Kafka) GetCommitBatchSize() int32 {
	if x != nil {
		return x.CommitBatchSize
	}
	return 0
}

func (x *Data_Kafka) GetCommitFlushInterval() *durationpb.Duration {
	if x != nil {
		return x.CommitFlushInterval
	}
	return nil
}

var File_conf_conf_proto protoreflect.FileDescriptor

const file_conf_conf_proto_rawDesc = "" +
	"\n" +
	"\x0fconf/conf.proto\x12\n" +
	"kratos.api\x1a\x1egoogle/protobuf/duration.proto\"\xa5\x02\n" +
	"\tBootstrap\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.kratos.api.ServerR\x06server\x12$\n" +
	"\x04data\x18\x02 \x01(\v2\x10.kratos.api.DataR\x04data\x12$\n" +
	"\x04auth\x18\x03 \x01(\v2\x10.kratos.api.AuthR\x04auth\x120\n" +
	"\bdispatch\x18\x04 \x01(\v2\x14.kratos.api.DispatchR\bdispatch\x123\n" +
	"\agateway\x18\x05 \x01(\v2\x19.kratos.api.GatewayConfigR\agateway\x129\n" +
	"\tmsgworker\x18\x06 \x01(\v2\x1b.kratos.api.MsgworkerConfigR\tmsgworker\"\xb8\x02\n" +
	"\x06Server\x12+\n" +
	"\x04http\x18\x01 \x01(\v2\x17.kratos.api.Server.HTTPR\x04http\x12+\n" +
	"\x04grpc\x18\x02 \x01(\v2\x17.kratos.api.Server.GRPCR\x04grpc\x1ai\n" +
	"\x04HTTP\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"\x85\f\n" +
	"\x04Data\x125\n" +
	"\bdatabase\x18\x01 \x01(\v2\x19.kratos.api.Data.DatabaseR\bdatabase\x12,\n" +
	"\x05redis\x18\x02 \x01(\v2\x16.kratos.api.Data.RedisR\x05redis\x122\n" +
	"\amongodb\x18\x03 \x01(\v2\x18.kratos.api.Data.MongoDBR\amongodb\x12,\n" +
	"\x05kafka\x18\x04 \x01(\v2\x16.kratos.api.Data.KafkaR\x05kafka\x1a\xcd\x01\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12$\n" +
	"\x0emax_open_conns\x18\x03 \x01(\x05R\fmaxOpenConns\x12$\n" +
	"\x0emax_idle_conns\x18\x04 \x01(\x05R\fmaxIdleConns\x12E\n" +
	"\x11conn_max_lifetime\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x0fconnMaxLifetime\x1a\xb3\x01\n" +
	"\x05Redis\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x1a\\\n" +
	"\aMongoDB\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\x12#\n" +
	"\rwrite_concern\x18\x03 \x01(\tR\fwriteConcern\x1a\xd1\x06\n" +
	"\x05Kafka\x12\x18\n" +
	"\abrokers\x18\x01 \x03(\tR\abrokers\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12%\n" +
	"\x0econsumer_group\x18\x03 \x01(\tR\rconsumerGroup\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x04 \x01(\x05R\tbatchSize\x12>\n" +
	"\rbatch_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\fbatchTimeout\x12 \n" +
	"\vcompression\x18\x06 \x01(\tR\vcompression\x12#\n" +
	"\rrequired_acks\x18\a \x01(\tR\frequiredAcks\x12\x14\n" +
	"\x05async\x18\b \x01(\bR\x05async\x12!\n" +
	"\fmax_attempts\x18\t \x01(\x05R\vmaxAttempts\x12>\n" +
	"\rwrite_timeout\x18\n" +
	" \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12<\n" +
	"\fread_timeout\x18\v \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12!\n" +
	"\fworker_count\x18\f \x01(\x05R\vworkerCount\x12\x1b\n" +
	"\tmin_bytes\x18\r \x01(\x05R\bminBytes\x12\x1b\n" +
	"\tmax_bytes\x18\x0e \x01(\x05R\bmaxBytes\x124\n" +
	"\bmax_wait\x18\x0f \x01(\v2\x19.google.protobuf.DurationR\amaxWait\x12B\n" +
	"\x0fcommit_interval\x18\x10 \x01(\v2\x19.google.protobuf.DurationR\x0ecommitInterval\x12\x1f\n" +
	"\vmax_retries\x18\x11 \x01(\x05R\n" +
	"maxRetries\x12!\n" +
	"\fstart_offset\x18\x12 \x01(\x03R\vstartOffset\x12*\n" +
	"\x11commit_batch_size\x18\x13 \x01(\x05R\x0fcommitBatchSize\x12M\n" +
	"\x15commit_flush_interval\x18\x14 \x01(\v2\x19.google.protobuf.DurationR\x13commitFlushInterval\"]\n" +
	"\x04Auth\x12\x1d\n" +
	"\n" +
	"jwt_secret\x18\x01 \x01(\tR\tjwtSecret\x126\n" +
	"\ttoken_ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\btokenTtl\"s\n" +
	"\vGatewayNode\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vgateway_url\x18\x02 \x01(\tR\n" +
	"gatewayUrl\x12*\n" +
	"\x11gateway_grpc_addr\x18\x03 \x01(\tR\x0fgatewayGrpcAddr\"\xc8\x02\n" +
	"\rGatewayConfig\x12H\n" +
	"\x12heartbeat_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\x12F\n" +
	"\x11heartbeat_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x10heartbeatTimeout\x12<\n" +
	"\fread_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\vreadTimeout\x12>\n" +
	"\rwrite_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fwriteTimeout\x12'\n" +
	"\x0fallowed_origins\x18\x05 \x03(\tR\x0eallowedOrigins\"\xdb\x01\n" +
	"\bDispatch\x123\n" +
	"\bgateways\x18\x01 \x03(\v2\x17.kratos.api.GatewayNodeR\bgateways\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12H\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\x124\n" +
	"\bnode_ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\anodeTtl\"C\n" +
	"\aGateway\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vgateway_url\x18\x02 \x01(\tR\n" +
	"gatewayUrl\"\xca\x02\n" +
	"\x0fMsgworkerConfig\x12E\n" +
	"\x11session_cache_ttl\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x0fsessionCacheTtl\x12,\n" +
	"\x12receipt_batch_size\x18\x02 \x01(\x05R\x10receiptBatchSize\x12M\n" +
	"\x15receipt_batch_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x13receiptBatchTimeout\x12(\n" +
	"\x10group_batch_size\x18\x04 \x01(\x05R\x0egroupBatchSize\x12I\n" +
	"\x13group_batch_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x11groupBatchTimeoutB\x1eZ\x1cnonoka-im/internal/conf;confb\x06proto3"

var (
	file_conf_conf_proto_rawDescOnce sync.Once
	file_conf_conf_proto_rawDescData []byte
)

func file_conf_conf_proto_rawDescGZIP() []byte {
	file_conf_conf_proto_rawDescOnce.Do(func() {
		file_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)))
	})
	return file_conf_conf_proto_rawDescData
}

var file_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: kratos.api.Bootstrap
	(*Server)(nil),              // 1: kratos.api.Server
	(*Data)(nil),                // 2: kratos.api.Data
	(*Auth)(nil),                // 3: kratos.api.Auth
	(*GatewayNode)(nil),         // 4: kratos.api.GatewayNode
	(*GatewayConfig)(nil),       // 5: kratos.api.GatewayConfig
	(*Dispatch)(nil),            // 6: kratos.api.Dispatch
	(*Gateway)(nil),             // 7: kratos.api.Gateway
	(*MsgworkerConfig)(nil),     // 8: kratos.api.MsgworkerConfig
	(*Server_HTTP)(nil),         // 9: kratos.api.Server.HTTP
	(*Server_GRPC)(nil),         // 10: kratos.api.Server.GRPC
	(*Data_Database)(nil),       // 11: kratos.api.Data.Database
	(*Data_Redis)(nil),          // 12: kratos.api.Data.Redis
	(*Data_MongoDB)(nil),        // 13: kratos.api.Data.MongoDB
	(*Data_Kafka)(nil),          // 14: kratos.api.Data.Kafka
	(*durationpb.Duration)(nil), // 15: google.protobuf.Duration
}
var file_conf_conf_proto_depIdxs = []int32{
	1,  // 0: kratos.api.Bootstrap.server:type_name -> kratos.api.Server
	2,  // 1: kratos.api.Bootstrap.data:type_name -> kratos.api.Data
	3,  // 2: kratos.api.Bootstrap.auth:type_name -> kratos.api.Auth
	6,  // 3: kratos.api.Bootstrap.dispatch:type_name -> kratos.api.Dispatch
	5,  // 4: kratos.api.Bootstrap.gateway:type_name -> kratos.api.GatewayConfig
	8,  // 5: kratos.api.Bootstrap.msgworker:type_name -> kratos.api.MsgworkerConfig
	9,  // 6: kratos.api.Server.http:type_name -> kratos.api.Server.HTTP
	10, // 7: kratos.api.Server.grpc:type_name -> kratos.api.Server.GRPC
	11, // 8: kratos.api.Data.database:type_name -> kratos.api.Data.Database
	12, // 9: kratos.api.Data.redis:type_name -> kratos.api.Data.Redis
	13, // 10: kratos.api.Data.mongodb:type_name -> kratos.api.Data.MongoDB
	14, // 11: kratos.api.Data.kafka:type_name -> kratos.api.Data.Kafka
	15, // 12: kratos.api.Auth.token_ttl:type_name -> google.protobuf.Duration
	15, // 13: kratos.api.GatewayConfig.heartbeat_interval:type_name -> google.protobuf.Duration
	15, // 14: kratos.api.GatewayConfig.heartbeat_timeout:type_name -> google.protobuf.Duration
	15, // 15: kratos.api.GatewayConfig.read_timeout:type_name -> google.protobuf.Duration
	15, // 16: kratos.api.GatewayConfig.write_timeout:type_name -> google.protobuf.Duration
	4,  // 17: kratos.api.Dispatch.gateways:type_name -> kratos.api.GatewayNode
	15, // 18: kratos.api.Dispatch.heartbeat_interval:type_name -> google.protobuf.Duration
	15, // 19: kratos.api.Dispatch.node_ttl:type_name -> google.protobuf.Duration
	15, // 20: kratos.api.MsgworkerConfig.session_cache_ttl:type_name -> google.protobuf.Duration
	15, // 21: kratos.api.MsgworkerConfig.receipt_batch_timeout:type_name -> google.protobuf.Duration
	15, // 22: kratos.api.MsgworkerConfig.group_batch_timeout:type_name -> google.protobuf.Duration
	15, // 23: kratos.api.Server.HTTP.timeout:type_name -> google.protobuf.Duration
	15, // 24: kratos.api.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	15, // 25: kratos.api.Data.Database.conn_max_lifetime:type_name -> google.protobuf.Duration
	15, // 26: kratos.api.Data.Redis.read_timeout:type_name -> google.protobuf.Duration
	15, // 27: kratos.api.Data.Redis.write_timeout:type_name -> google.protobuf.Duration
	15, // 28: kratos.api.Data.Kafka.batch_timeout:type_name -> google.protobuf.Duration
	15, // 29: kratos.api.Data.Kafka.write_timeout:type_name -> google.protobuf.Duration
	15, // 30: kratos.api.Data.Kafka.read_timeout:type_name -> google.protobuf.Duration
	15, // 31: kratos.api.Data.Kafka.max_wait:type_name -> google.protobuf.Duration
	15, // 32: kratos.api.Data.Kafka.commit_interval:type_name -> google.protobuf.Duration
	15, // 33: kratos.api.Data.Kafka.commit_flush_interval:type_name -> google.protobuf.Duration
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_conf_conf_proto_init() }
func file_conf_conf_proto_init() {
	if File_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_conf_proto_rawDesc), len(file_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_conf_proto_goTypes,
		DependencyIndexes: file_conf_conf_proto_depIdxs,
		MessageInfos:      file_conf_conf_proto_msgTypes,
	}.Build()
	File_conf_conf_proto = out.File
	file_conf_conf_proto_goTypes = nil
	file_conf_conf_proto_depIdxs = nil
}
